// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// GoModToken represents a Token generated by LangSpec (IDs match compiler symbol table).
type GoModToken = lexarch.TokenKind

const (
	GoMod_STD__TokArrow GoModToken = 2
	GoMod_STD__TokEquals GoModToken = 3
	GoMod_STD__TokFloat GoModToken = 4
	GoMod_STD__TokKWGo GoModToken = 5
	GoMod_STD__TokKWGodebug GoModToken = 6
	GoMod_STD__TokKWReplace GoModToken = 7
	GoMod_STD__TokKWToolchain GoModToken = 8
	GoMod_STD__TokModulePath GoModToken = 9
	GoMod_STD__TokParenClose GoModToken = 10
	GoMod_STD__TokParenOpen GoModToken = 11
	GoMod_STD__TokVersion GoModToken = 12
	GoMod_TokArrow GoModToken = 13
	GoMod_TokBracketClose GoModToken = 14
	GoMod_TokBracketOpen GoModToken = 15
	GoMod_TokComma GoModToken = 16
	GoMod_TokEOF GoModToken = 17
	GoMod_TokEquals GoModToken = 18
	GoMod_TokFloat GoModToken = 19
	GoMod_TokKWExclude GoModToken = 20
	GoMod_TokKWGo GoModToken = 21
	GoMod_TokKWGodebug GoModToken = 22
	GoMod_TokKWModule GoModToken = 23
	GoMod_TokKWReplace GoModToken = 24
	GoMod_TokKWRequire GoModToken = 25
	GoMod_TokKWRetract GoModToken = 26
	GoMod_TokKWTool GoModToken = 27
	GoMod_TokKWToolchain GoModToken = 28
	GoMod_TokLineComment GoModToken = 29
	GoMod_TokModulePath GoModToken = 30
	GoMod_TokParenClose GoModToken = 31
	GoMod_TokParenOpen GoModToken = 32
	GoMod_TokVersion GoModToken = 33
	GoMod_TokWhitespace GoModToken = 34
)

var GoModTokenNames = [...]string{
	"STD__TokArrow",
	"STD__TokEquals",
	"STD__TokFloat",
	"STD__TokKWGo",
	"STD__TokKWGodebug",
	"STD__TokKWReplace",
	"STD__TokKWToolchain",
	"STD__TokModulePath",
	"STD__TokParenClose",
	"STD__TokParenOpen",
	"STD__TokVersion",
	"TokArrow",
	"TokBracketClose",
	"TokBracketOpen",
	"TokComma",
	"TokEOF",
	"TokEquals",
	"TokFloat",
	"TokKWExclude",
	"TokKWGo",
	"TokKWGodebug",
	"TokKWModule",
	"TokKWReplace",
	"TokKWRequire",
	"TokKWRetract",
	"TokKWTool",
	"TokKWToolchain",
	"TokLineComment",
	"TokModulePath",
	"TokParenClose",
	"TokParenOpen",
	"TokVersion",
	"TokWhitespace",
}

func GoModTokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(GoModTokenNames) {
		return "GoModToken(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoModTokenNames[t-2]
}

func GoModTokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(GoModTokenNames) {
		return "", false
	}
	return GoModTokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(GoModTokenTokenKindStringResolver)
}

// GoModNode represents a Node generated by LangSpec (IDs match compiler symbol table).
type GoModNode uint32

const (
	GoMod_BLOCK GoModNode = 1
	GoMod_ERROR_NODE GoModNode = 2
	GoMod_EXCLUDE_STATEMENT GoModNode = 3
	GoMod_MODULE_REFERENCE GoModNode = 4
	GoMod_MODULE_STATEMENT GoModNode = 5
	GoMod_NodeExcludeStatement GoModNode = 6
	GoMod_NodeGodebugReference GoModNode = 7
	GoMod_NodeModuleName GoModNode = 8
	GoMod_NodeModuleReference GoModNode = 9
	GoMod_NodeModuleReferenceIdent GoModNode = 10
	GoMod_NodeModuleReferenceVersion GoModNode = 11
	GoMod_NodeModuleStatement GoModNode = 12
	GoMod_NodeProgram GoModNode = 13
	GoMod_NodeReplaceReference GoModNode = 14
	GoMod_NodeRequireStatement GoModNode = 15
	GoMod_NodeRetractHigh GoModNode = 16
	GoMod_NodeRetractLow GoModNode = 17
	GoMod_NodeRetractRange GoModNode = 18
	GoMod_NodeRetractReference GoModNode = 19
	GoMod_NodeRetractSingle GoModNode = 20
	GoMod_NodeRetractStatement GoModNode = 21
	GoMod_NodeToolPath GoModNode = 22
	GoMod_NodeToolReference GoModNode = 23
	GoMod_NodeToolStatement GoModNode = 24
	GoMod_REQUIRE_STATEMENT GoModNode = 25
	GoMod_RETRACT_RANGE GoModNode = 26
	GoMod_RETRACT_REFERENCE GoModNode = 27
	GoMod_RETRACT_STATEMENT GoModNode = 28
	GoMod_STD__GODEBUG_REFERENCE GoModNode = 29
	GoMod_STD__NodeGoDecl GoModNode = 30
	GoMod_STD__NodeGoVersion GoModNode = 31
	GoMod_STD__NodeGodebugKey GoModNode = 32
	GoMod_STD__NodeGodebugReference GoModNode = 33
	GoMod_STD__NodeGodebugStatement GoModNode = 34
	GoMod_STD__NodeGodebugValue GoModNode = 35
	GoMod_STD__NodeReplaceOriginal GoModNode = 36
	GoMod_STD__NodeReplaceOriginalVersion GoModNode = 37
	GoMod_STD__NodeReplaceReference GoModNode = 38
	GoMod_STD__NodeReplaceStatement GoModNode = 39
	GoMod_STD__NodeReplaceTarget GoModNode = 40
	GoMod_STD__NodeReplaceTargetVersion GoModNode = 41
	GoMod_STD__NodeToolchainName GoModNode = 42
	GoMod_STD__NodeToolchainStatement GoModNode = 43
	GoMod_STD__REPLACE_REFERENCE GoModNode = 44
	GoMod_TOOL_REFERENCE GoModNode = 45
	GoMod_TOOL_STATEMENT GoModNode = 46
	GoMod_gr_BLOCK GoModNode = 47
)

var GoModNodeNames = [...]string{
	"BLOCK",
	"ERROR_NODE",
	"EXCLUDE_STATEMENT",
	"MODULE_REFERENCE",
	"MODULE_STATEMENT",
	"NodeExcludeStatement",
	"NodeGodebugReference",
	"NodeModuleName",
	"NodeModuleReference",
	"NodeModuleReferenceIdent",
	"NodeModuleReferenceVersion",
	"NodeModuleStatement",
	"NodeProgram",
	"NodeReplaceReference",
	"NodeRequireStatement",
	"NodeRetractHigh",
	"NodeRetractLow",
	"NodeRetractRange",
	"NodeRetractReference",
	"NodeRetractSingle",
	"NodeRetractStatement",
	"NodeToolPath",
	"NodeToolReference",
	"NodeToolStatement",
	"REQUIRE_STATEMENT",
	"RETRACT_RANGE",
	"RETRACT_REFERENCE",
	"RETRACT_STATEMENT",
	"STD__GODEBUG_REFERENCE",
	"STD__NodeGoDecl",
	"STD__NodeGoVersion",
	"STD__NodeGodebugKey",
	"STD__NodeGodebugReference",
	"STD__NodeGodebugStatement",
	"STD__NodeGodebugValue",
	"STD__NodeReplaceOriginal",
	"STD__NodeReplaceOriginalVersion",
	"STD__NodeReplaceReference",
	"STD__NodeReplaceStatement",
	"STD__NodeReplaceTarget",
	"STD__NodeReplaceTargetVersion",
	"STD__NodeToolchainName",
	"STD__NodeToolchainStatement",
	"STD__REPLACE_REFERENCE",
	"TOOL_REFERENCE",
	"TOOL_STATEMENT",
	"gr_BLOCK",
}

func (t GoModNode) String() string {
	if t < 1 || int(t-1) >= len(GoModNodeNames) {
		return "GoModNode(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoModNodeNames[t-1]
}
