// Code generated by LangSpec. DO NOT EDIT.

package artifacts

// GoModToken represents a Token generated by LangSpec
type GoModToken string

const (
	GoMod_TokArrow GoModToken = "TokArrow"
	GoMod_TokBracketClose GoModToken = "TokBracketClose"
	GoMod_TokBracketOpen GoModToken = "TokBracketOpen"
	GoMod_TokComma GoModToken = "TokComma"
	GoMod_TokEquals GoModToken = "TokEquals"
	GoMod_TokFloat GoModToken = "TokFloat"
	GoMod_TokKWExclude GoModToken = "TokKWExclude"
	GoMod_TokKWGo GoModToken = "TokKWGo"
	GoMod_TokKWGodebug GoModToken = "TokKWGodebug"
	GoMod_TokKWModule GoModToken = "TokKWModule"
	GoMod_TokKWReplace GoModToken = "TokKWReplace"
	GoMod_TokKWRequire GoModToken = "TokKWRequire"
	GoMod_TokKWRetract GoModToken = "TokKWRetract"
	GoMod_TokKWTool GoModToken = "TokKWTool"
	GoMod_TokKWToolchain GoModToken = "TokKWToolchain"
	GoMod_TokLineComment GoModToken = "TokLineComment"
	GoMod_TokModulePath GoModToken = "TokModulePath"
	GoMod_TokParenClose GoModToken = "TokParenClose"
	GoMod_TokParenOpen GoModToken = "TokParenOpen"
	GoMod_TokVersion GoModToken = "TokVersion"
	GoMod_TokWhitespace GoModToken = "TokWhitespace"
)

// GoModNode represents a Node generated by LangSpec
type GoModNode string

const (
	GoMod_NodeExcludeStatement GoModNode = "NodeExcludeStatement"
	GoMod_NodeGoDecl GoModNode = "NodeGoDecl"
	GoMod_NodeGoVersion GoModNode = "NodeGoVersion"
	GoMod_NodeGodebugKey GoModNode = "NodeGodebugKey"
	GoMod_NodeGodebugReference GoModNode = "NodeGodebugReference"
	GoMod_NodeGodebugStatement GoModNode = "NodeGodebugStatement"
	GoMod_NodeGodebugValue GoModNode = "NodeGodebugValue"
	GoMod_NodeModuleName GoModNode = "NodeModuleName"
	GoMod_NodeModuleReference GoModNode = "NodeModuleReference"
	GoMod_NodeModuleReferenceIdent GoModNode = "NodeModuleReferenceIdent"
	GoMod_NodeModuleReferenceVersion GoModNode = "NodeModuleReferenceVersion"
	GoMod_NodeModuleStatement GoModNode = "NodeModuleStatement"
	GoMod_NodeProgram GoModNode = "NodeProgram"
	GoMod_NodeReplaceOriginal GoModNode = "NodeReplaceOriginal"
	GoMod_NodeReplaceOriginalVersion GoModNode = "NodeReplaceOriginalVersion"
	GoMod_NodeReplaceReference GoModNode = "NodeReplaceReference"
	GoMod_NodeReplaceStatement GoModNode = "NodeReplaceStatement"
	GoMod_NodeReplaceTarget GoModNode = "NodeReplaceTarget"
	GoMod_NodeReplaceTargetVersion GoModNode = "NodeReplaceTargetVersion"
	GoMod_NodeRequireStatement GoModNode = "NodeRequireStatement"
	GoMod_NodeRetractHigh GoModNode = "NodeRetractHigh"
	GoMod_NodeRetractLow GoModNode = "NodeRetractLow"
	GoMod_NodeRetractRange GoModNode = "NodeRetractRange"
	GoMod_NodeRetractReference GoModNode = "NodeRetractReference"
	GoMod_NodeRetractSingle GoModNode = "NodeRetractSingle"
	GoMod_NodeRetractStatement GoModNode = "NodeRetractStatement"
	GoMod_NodeToolPath GoModNode = "NodeToolPath"
	GoMod_NodeToolStatement GoModNode = "NodeToolStatement"
	GoMod_NodeToolchainName GoModNode = "NodeToolchainName"
	GoMod_NodeToolchainStatement GoModNode = "NodeToolchainStatement"
)
