// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import "strconv"

// GoModToken represents a Token generated by LangSpec (IDs match compiler symbol table).
type GoModToken uint32

const (
	GoMod_TokArrow GoModToken = 2
	GoMod_TokBracketClose GoModToken = 3
	GoMod_TokBracketOpen GoModToken = 4
	GoMod_TokComma GoModToken = 5
	GoMod_TokEOF GoModToken = 6
	GoMod_TokEquals GoModToken = 7
	GoMod_TokFloat GoModToken = 8
	GoMod_TokKWExclude GoModToken = 9
	GoMod_TokKWGo GoModToken = 10
	GoMod_TokKWGodebug GoModToken = 11
	GoMod_TokKWModule GoModToken = 12
	GoMod_TokKWReplace GoModToken = 13
	GoMod_TokKWRequire GoModToken = 14
	GoMod_TokKWRetract GoModToken = 15
	GoMod_TokKWTool GoModToken = 16
	GoMod_TokKWToolchain GoModToken = 17
	GoMod_TokLineComment GoModToken = 18
	GoMod_TokModulePath GoModToken = 19
	GoMod_TokParenClose GoModToken = 20
	GoMod_TokParenOpen GoModToken = 21
	GoMod_TokVersion GoModToken = 22
	GoMod_TokWhitespace GoModToken = 23
)

var GoModTokenNames = [...]string{
	"TokArrow",
	"TokBracketClose",
	"TokBracketOpen",
	"TokComma",
	"TokEOF",
	"TokEquals",
	"TokFloat",
	"TokKWExclude",
	"TokKWGo",
	"TokKWGodebug",
	"TokKWModule",
	"TokKWReplace",
	"TokKWRequire",
	"TokKWRetract",
	"TokKWTool",
	"TokKWToolchain",
	"TokLineComment",
	"TokModulePath",
	"TokParenClose",
	"TokParenOpen",
	"TokVersion",
	"TokWhitespace",
}

func (t GoModToken) String() string {
	if t < 2 || int(t-2) >= len(GoModTokenNames) {
		return "GoModToken(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoModTokenNames[t-2]
}

// GoModNode represents a Node generated by LangSpec (IDs match compiler symbol table).
type GoModNode uint32

const (
	GoMod_BLOCK GoModNode = 1
	GoMod_ERROR_NODE GoModNode = 2
	GoMod_EXCLUDE_STATEMENT GoModNode = 3
	GoMod_GODEBUG_REFERENCE GoModNode = 4
	GoMod_GODEBUG_STATEMENT GoModNode = 5
	GoMod_GO_DECLARATION GoModNode = 6
	GoMod_MODULE_REFERENCE GoModNode = 7
	GoMod_MODULE_STATEMENT GoModNode = 8
	GoMod_NodeExcludeStatement GoModNode = 9
	GoMod_NodeGoDecl GoModNode = 10
	GoMod_NodeGoVersion GoModNode = 11
	GoMod_NodeGodebugKey GoModNode = 12
	GoMod_NodeGodebugReference GoModNode = 13
	GoMod_NodeGodebugStatement GoModNode = 14
	GoMod_NodeGodebugValue GoModNode = 15
	GoMod_NodeModuleName GoModNode = 16
	GoMod_NodeModuleReference GoModNode = 17
	GoMod_NodeModuleReferenceIdent GoModNode = 18
	GoMod_NodeModuleReferenceVersion GoModNode = 19
	GoMod_NodeModuleStatement GoModNode = 20
	GoMod_NodeProgram GoModNode = 21
	GoMod_NodeReplaceOriginal GoModNode = 22
	GoMod_NodeReplaceOriginalVersion GoModNode = 23
	GoMod_NodeReplaceReference GoModNode = 24
	GoMod_NodeReplaceStatement GoModNode = 25
	GoMod_NodeReplaceTarget GoModNode = 26
	GoMod_NodeReplaceTargetVersion GoModNode = 27
	GoMod_NodeRequireStatement GoModNode = 28
	GoMod_NodeRetractHigh GoModNode = 29
	GoMod_NodeRetractLow GoModNode = 30
	GoMod_NodeRetractRange GoModNode = 31
	GoMod_NodeRetractReference GoModNode = 32
	GoMod_NodeRetractSingle GoModNode = 33
	GoMod_NodeRetractStatement GoModNode = 34
	GoMod_NodeToolPath GoModNode = 35
	GoMod_NodeToolReference GoModNode = 36
	GoMod_NodeToolStatement GoModNode = 37
	GoMod_NodeToolchainName GoModNode = 38
	GoMod_NodeToolchainStatement GoModNode = 39
	GoMod_REPLACE_REFERENCE GoModNode = 40
	GoMod_REPLACE_STATEMENT GoModNode = 41
	GoMod_REQUIRE_STATEMENT GoModNode = 42
	GoMod_RETRACT_RANGE GoModNode = 43
	GoMod_RETRACT_REFERENCE GoModNode = 44
	GoMod_RETRACT_STATEMENT GoModNode = 45
	GoMod_TOOLCHAIN_STATEMENT GoModNode = 46
	GoMod_TOOL_REFERENCE GoModNode = 47
	GoMod_TOOL_STATEMENT GoModNode = 48
	GoMod_gr_BLOCK GoModNode = 49
)

var GoModNodeNames = [...]string{
	"BLOCK",
	"ERROR_NODE",
	"EXCLUDE_STATEMENT",
	"GODEBUG_REFERENCE",
	"GODEBUG_STATEMENT",
	"GO_DECLARATION",
	"MODULE_REFERENCE",
	"MODULE_STATEMENT",
	"NodeExcludeStatement",
	"NodeGoDecl",
	"NodeGoVersion",
	"NodeGodebugKey",
	"NodeGodebugReference",
	"NodeGodebugStatement",
	"NodeGodebugValue",
	"NodeModuleName",
	"NodeModuleReference",
	"NodeModuleReferenceIdent",
	"NodeModuleReferenceVersion",
	"NodeModuleStatement",
	"NodeProgram",
	"NodeReplaceOriginal",
	"NodeReplaceOriginalVersion",
	"NodeReplaceReference",
	"NodeReplaceStatement",
	"NodeReplaceTarget",
	"NodeReplaceTargetVersion",
	"NodeRequireStatement",
	"NodeRetractHigh",
	"NodeRetractLow",
	"NodeRetractRange",
	"NodeRetractReference",
	"NodeRetractSingle",
	"NodeRetractStatement",
	"NodeToolPath",
	"NodeToolReference",
	"NodeToolStatement",
	"NodeToolchainName",
	"NodeToolchainStatement",
	"REPLACE_REFERENCE",
	"REPLACE_STATEMENT",
	"REQUIRE_STATEMENT",
	"RETRACT_RANGE",
	"RETRACT_REFERENCE",
	"RETRACT_STATEMENT",
	"TOOLCHAIN_STATEMENT",
	"TOOL_REFERENCE",
	"TOOL_STATEMENT",
	"gr_BLOCK",
}

func (t GoModNode) String() string {
	if t < 1 || int(t-1) >= len(GoModNodeNames) {
		return "GoModNode(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoModNodeNames[t-1]
}
