// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// GoWorkToken represents a Token generated by LangSpec (IDs match compiler symbol table).
type GoWorkToken = lexarch.TokenKind

const (
	GoWork_TokArrow GoWorkToken = 2
	GoWork_TokEOF GoWorkToken = 3
	GoWork_TokEquals GoWorkToken = 4
	GoWork_TokFloat GoWorkToken = 5
	GoWork_TokKWGo GoWorkToken = 6
	GoWork_TokKWGodebug GoWorkToken = 7
	GoWork_TokKWReplace GoWorkToken = 8
	GoWork_TokKWToolchain GoWorkToken = 9
	GoWork_TokKWUse GoWorkToken = 10
	GoWork_TokLineComment GoWorkToken = 11
	GoWork_TokModulePath GoWorkToken = 12
	GoWork_TokParenClose GoWorkToken = 13
	GoWork_TokParenOpen GoWorkToken = 14
	GoWork_TokVersion GoWorkToken = 15
	GoWork_TokWhitespace GoWorkToken = 16
)

var GoWorkTokenNames = [...]string{
	"TokArrow",
	"TokEOF",
	"TokEquals",
	"TokFloat",
	"TokKWGo",
	"TokKWGodebug",
	"TokKWReplace",
	"TokKWToolchain",
	"TokKWUse",
	"TokLineComment",
	"TokModulePath",
	"TokParenClose",
	"TokParenOpen",
	"TokVersion",
	"TokWhitespace",
}

func GoWorkTokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(GoWorkTokenNames) {
		return "GoWorkToken(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoWorkTokenNames[t-2]
}

func GoWorkTokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(GoWorkTokenNames) {
		return "", false
	}
	return GoWorkTokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(GoWorkTokenTokenKindStringResolver)
}

// GoWorkNode represents a Node generated by LangSpec (IDs match compiler symbol table).
type GoWorkNode uint32

const (
	GoWork_BLOCK GoWorkNode = 1
	GoWork_ERROR_NODE GoWorkNode = 2
	GoWork_GODEBUG_REFERENCE GoWorkNode = 3
	GoWork_GODEBUG_STATEMENT GoWorkNode = 4
	GoWork_GO_DECLARATION GoWorkNode = 5
	GoWork_NodeGoDecl GoWorkNode = 6
	GoWork_NodeGoVersion GoWorkNode = 7
	GoWork_NodeGodebugKey GoWorkNode = 8
	GoWork_NodeGodebugReference GoWorkNode = 9
	GoWork_NodeGodebugStatement GoWorkNode = 10
	GoWork_NodeGodebugValue GoWorkNode = 11
	GoWork_NodeProgram GoWorkNode = 12
	GoWork_NodeReplaceOriginal GoWorkNode = 13
	GoWork_NodeReplaceOriginalVersion GoWorkNode = 14
	GoWork_NodeReplaceReference GoWorkNode = 15
	GoWork_NodeReplaceStatement GoWorkNode = 16
	GoWork_NodeReplaceTarget GoWorkNode = 17
	GoWork_NodeReplaceTargetVersion GoWorkNode = 18
	GoWork_NodeToolchainName GoWorkNode = 19
	GoWork_NodeToolchainStatement GoWorkNode = 20
	GoWork_NodeUsePath GoWorkNode = 21
	GoWork_NodeUseReference GoWorkNode = 22
	GoWork_NodeUseStatement GoWorkNode = 23
	GoWork_REPLACE_REFERENCE GoWorkNode = 24
	GoWork_REPLACE_STATEMENT GoWorkNode = 25
	GoWork_TOOLCHAIN_STATEMENT GoWorkNode = 26
	GoWork_USE_REFERENCE GoWorkNode = 27
	GoWork_USE_STATEMENT GoWorkNode = 28
	GoWork_gr_BLOCK GoWorkNode = 29
)

var GoWorkNodeNames = [...]string{
	"BLOCK",
	"ERROR_NODE",
	"GODEBUG_REFERENCE",
	"GODEBUG_STATEMENT",
	"GO_DECLARATION",
	"NodeGoDecl",
	"NodeGoVersion",
	"NodeGodebugKey",
	"NodeGodebugReference",
	"NodeGodebugStatement",
	"NodeGodebugValue",
	"NodeProgram",
	"NodeReplaceOriginal",
	"NodeReplaceOriginalVersion",
	"NodeReplaceReference",
	"NodeReplaceStatement",
	"NodeReplaceTarget",
	"NodeReplaceTargetVersion",
	"NodeToolchainName",
	"NodeToolchainStatement",
	"NodeUsePath",
	"NodeUseReference",
	"NodeUseStatement",
	"REPLACE_REFERENCE",
	"REPLACE_STATEMENT",
	"TOOLCHAIN_STATEMENT",
	"USE_REFERENCE",
	"USE_STATEMENT",
	"gr_BLOCK",
}

func (t GoWorkNode) String() string {
	if t < 1 || int(t-1) >= len(GoWorkNodeNames) {
		return "GoWorkNode(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoWorkNodeNames[t-1]
}
