// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// GoWorkToken represents a Token generated by LangSpec (IDs match compiler symbol table).
type GoWorkToken = lexarch.TokenKind

const (
	GoWork_TokArrow GoWorkToken = 2
	GoWork_TokEOF GoWorkToken = 3
	GoWork_TokEquals GoWorkToken = 4
	GoWork_TokFloat GoWorkToken = 5
	GoWork_TokKWGo GoWorkToken = 6
	GoWork_TokKWGodebug GoWorkToken = 7
	GoWork_TokKWReplace GoWorkToken = 8
	GoWork_TokKWToolchain GoWorkToken = 9
	GoWork_TokKWUse GoWorkToken = 10
	GoWork_TokLineComment GoWorkToken = 11
	GoWork_TokModulePath GoWorkToken = 12
	GoWork_TokParenClose GoWorkToken = 13
	GoWork_TokParenOpen GoWorkToken = 14
	GoWork_TokVersion GoWorkToken = 15
	GoWork_TokWhitespace GoWorkToken = 16
)

var GoWorkTokenNames = [...]string{
	"TokArrow",
	"TokEOF",
	"TokEquals",
	"TokFloat",
	"TokKWGo",
	"TokKWGodebug",
	"TokKWReplace",
	"TokKWToolchain",
	"TokKWUse",
	"TokLineComment",
	"TokModulePath",
	"TokParenClose",
	"TokParenOpen",
	"TokVersion",
	"TokWhitespace",
}

func GoWorkTokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(GoWorkTokenNames) {
		return "GoWorkToken(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoWorkTokenNames[t-2]
}

func GoWorkTokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(GoWorkTokenNames) {
		return "", false
	}
	return GoWorkTokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(GoWorkTokenTokenKindStringResolver)
}

// GoWorkNode represents a Node generated by LangSpec (IDs match compiler symbol table).
type GoWorkNode uint32

const (
	GoWork_BLOCK GoWorkNode = 1
	GoWork_ERROR_NODE GoWorkNode = 2
	GoWork_NodeGodebugReference GoWorkNode = 3
	GoWork_NodeProgram GoWorkNode = 4
	GoWork_NodeReplaceReference GoWorkNode = 5
	GoWork_NodeUsePath GoWorkNode = 6
	GoWork_NodeUseReference GoWorkNode = 7
	GoWork_NodeUseStatement GoWorkNode = 8
	GoWork_STD__GODEBUG_REFERENCE GoWorkNode = 9
	GoWork_STD__NodeGoDecl GoWorkNode = 10
	GoWork_STD__NodeGoVersion GoWorkNode = 11
	GoWork_STD__NodeGodebugKey GoWorkNode = 12
	GoWork_STD__NodeGodebugReference GoWorkNode = 13
	GoWork_STD__NodeGodebugStatement GoWorkNode = 14
	GoWork_STD__NodeGodebugValue GoWorkNode = 15
	GoWork_STD__NodeReplaceOriginal GoWorkNode = 16
	GoWork_STD__NodeReplaceOriginalVersion GoWorkNode = 17
	GoWork_STD__NodeReplaceReference GoWorkNode = 18
	GoWork_STD__NodeReplaceStatement GoWorkNode = 19
	GoWork_STD__NodeReplaceTarget GoWorkNode = 20
	GoWork_STD__NodeReplaceTargetVersion GoWorkNode = 21
	GoWork_STD__NodeToolchainName GoWorkNode = 22
	GoWork_STD__NodeToolchainStatement GoWorkNode = 23
	GoWork_STD__REPLACE_REFERENCE GoWorkNode = 24
	GoWork_USE_REFERENCE GoWorkNode = 25
	GoWork_USE_STATEMENT GoWorkNode = 26
	GoWork_gr_BLOCK GoWorkNode = 27
)

var GoWorkNodeNames = [...]string{
	"BLOCK",
	"ERROR_NODE",
	"NodeGodebugReference",
	"NodeProgram",
	"NodeReplaceReference",
	"NodeUsePath",
	"NodeUseReference",
	"NodeUseStatement",
	"STD__GODEBUG_REFERENCE",
	"STD__NodeGoDecl",
	"STD__NodeGoVersion",
	"STD__NodeGodebugKey",
	"STD__NodeGodebugReference",
	"STD__NodeGodebugStatement",
	"STD__NodeGodebugValue",
	"STD__NodeReplaceOriginal",
	"STD__NodeReplaceOriginalVersion",
	"STD__NodeReplaceReference",
	"STD__NodeReplaceStatement",
	"STD__NodeReplaceTarget",
	"STD__NodeReplaceTargetVersion",
	"STD__NodeToolchainName",
	"STD__NodeToolchainStatement",
	"STD__REPLACE_REFERENCE",
	"USE_REFERENCE",
	"USE_STATEMENT",
	"gr_BLOCK",
}

func (t GoWorkNode) String() string {
	if t < 1 || int(t-1) >= len(GoWorkNodeNames) {
		return "GoWorkNode(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return GoWorkNodeNames[t-1]
}
