// Code generated by LangSpec. DO NOT EDIT.

package artifacts

// GoWorkToken represents a Token generated by LangSpec
type GoWorkToken string

const (
	GoWork_TokArrow GoWorkToken = "TokArrow"
	GoWork_TokEquals GoWorkToken = "TokEquals"
	GoWork_TokFloat GoWorkToken = "TokFloat"
	GoWork_TokKWGo GoWorkToken = "TokKWGo"
	GoWork_TokKWGodebug GoWorkToken = "TokKWGodebug"
	GoWork_TokKWReplace GoWorkToken = "TokKWReplace"
	GoWork_TokKWToolchain GoWorkToken = "TokKWToolchain"
	GoWork_TokKWUse GoWorkToken = "TokKWUse"
	GoWork_TokLineComment GoWorkToken = "TokLineComment"
	GoWork_TokModulePath GoWorkToken = "TokModulePath"
	GoWork_TokParenClose GoWorkToken = "TokParenClose"
	GoWork_TokParenOpen GoWorkToken = "TokParenOpen"
	GoWork_TokVersion GoWorkToken = "TokVersion"
	GoWork_TokWhitespace GoWorkToken = "TokWhitespace"
)

// GoWorkNode represents a Node generated by LangSpec
type GoWorkNode string

const (
	GoWork_NodeGoDecl GoWorkNode = "NodeGoDecl"
	GoWork_NodeGoVersion GoWorkNode = "NodeGoVersion"
	GoWork_NodeGodebugKey GoWorkNode = "NodeGodebugKey"
	GoWork_NodeGodebugReference GoWorkNode = "NodeGodebugReference"
	GoWork_NodeGodebugStatement GoWorkNode = "NodeGodebugStatement"
	GoWork_NodeGodebugValue GoWorkNode = "NodeGodebugValue"
	GoWork_NodeProgram GoWorkNode = "NodeProgram"
	GoWork_NodeReplaceOriginal GoWorkNode = "NodeReplaceOriginal"
	GoWork_NodeReplaceOriginalVersion GoWorkNode = "NodeReplaceOriginalVersion"
	GoWork_NodeReplaceReference GoWorkNode = "NodeReplaceReference"
	GoWork_NodeReplaceStatement GoWorkNode = "NodeReplaceStatement"
	GoWork_NodeReplaceTarget GoWorkNode = "NodeReplaceTarget"
	GoWork_NodeReplaceTargetVersion GoWorkNode = "NodeReplaceTargetVersion"
	GoWork_NodeToolchainName GoWorkNode = "NodeToolchainName"
	GoWork_NodeToolchainStatement GoWorkNode = "NodeToolchainStatement"
	GoWork_NodeUsePath GoWorkNode = "NodeUsePath"
	GoWork_NodeUseStatement GoWorkNode = "NodeUseStatement"
)
