// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokBlockComment Token = 2
	TokBraceClose Token = 3
	TokBraceOpen Token = 4
	TokBracketClose Token = 5
	TokBracketOpen Token = 6
	TokComma Token = 7
	TokDollar Token = 8
	TokEOF Token = 9
	TokEmptyString Token = 10
	TokEquals Token = 11
	TokIdentifier Token = 12
	TokInteger Token = 13
	TokInterpolationEnd Token = 14
	TokInterpolationStart Token = 15
	TokKWAliases Token = 16
	TokKWArtifacts Token = 17
	TokKWConfirm Token = 18
	TokKWDefined Token = 19
	TokKWDependsOn Token = 20
	TokKWDynamic Token = 21
	TokKWEnv Token = 22
	TokKWEquals Token = 23
	TokKWFalse Token = 24
	TokKWGlob Token = 25
	TokKWHelp Token = 26
	TokKWHidden Token = 27
	TokKWIn Token = 28
	TokKWInputs Token = 29
	TokKWInteractive Token = 30
	TokKWMatrix Token = 31
	TokKWNotDefined Token = 32
	TokKWNotEquals Token = 33
	TokKWOptional Token = 34
	TokKWOutputs Token = 35
	TokKWParam Token = 36
	TokKWParams Token = 37
	TokKWPath Token = 38
	TokKWRun Token = 39
	TokKWTarget Token = 40
	TokKWTrue Token = 41
	TokKWVolatile Token = 42
	TokKWWhen Token = 43
	TokKWWorkingDir Token = 44
	TokLineComment Token = 45
	TokMultilineStringEnd Token = 46
	TokMultilineStringStart Token = 47
	TokMultilineStringText Token = 48
	TokNewLine Token = 49
	TokParenClose Token = 50
	TokParenOpen Token = 51
	TokQuestion Token = 52
	TokStringEnd Token = 53
	TokStringEscape Token = 54
	TokStringLiteral Token = 55
	TokStringStart Token = 56
	TokWhitespace Token = 57
)

var TokenNames = [...]string{
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokComma",
	"TokDollar",
	"TokEOF",
	"TokEmptyString",
	"TokEquals",
	"TokIdentifier",
	"TokInteger",
	"TokInterpolationEnd",
	"TokInterpolationStart",
	"TokKWAliases",
	"TokKWArtifacts",
	"TokKWConfirm",
	"TokKWDefined",
	"TokKWDependsOn",
	"TokKWDynamic",
	"TokKWEnv",
	"TokKWEquals",
	"TokKWFalse",
	"TokKWGlob",
	"TokKWHelp",
	"TokKWHidden",
	"TokKWIn",
	"TokKWInputs",
	"TokKWInteractive",
	"TokKWMatrix",
	"TokKWNotDefined",
	"TokKWNotEquals",
	"TokKWOptional",
	"TokKWOutputs",
	"TokKWParam",
	"TokKWParams",
	"TokKWPath",
	"TokKWRun",
	"TokKWTarget",
	"TokKWTrue",
	"TokKWVolatile",
	"TokKWWhen",
	"TokKWWorkingDir",
	"TokLineComment",
	"TokMultilineStringEnd",
	"TokMultilineStringStart",
	"TokMultilineStringText",
	"TokNewLine",
	"TokParenClose",
	"TokParenOpen",
	"TokQuestion",
	"TokStringEnd",
	"TokStringEscape",
	"TokStringLiteral",
	"TokStringStart",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	ALIASES_DECLARATION Node = 1
	ARTIFACTS_BLOCK Node = 2
	CONDITIONAL_BLOCK Node = 3
	CONDITIONAL_TARGET Node = 4
	DEFINES Node = 5
	DEPENDENCY_OPTIONS Node = 6
	DEPENDENCY_PARAMS Node = 7
	DEPENDENCY_PARAM_CONTENT Node = 8
	DEPENDENCY_PARAM_REF Node = 9
	DEPENDS_ON Node = 10
	DYNAMIC_ARRAY Node = 11
	DYNAMIC_STATEMENT Node = 12
	EMPTY_STRING Node = 13
	ENV_DECLARATION Node = 14
	EQUALS Node = 15
	ERROR_NODE Node = 16
	GLOB Node = 17
	GLOB_ARGS Node = 18
	GLOB_BASE_DIR Node = 19
	GLOB_KWARG Node = 20
	HELP_STATEMENT Node = 21
	HIDDEN_STATEMENT Node = 22
	INPUTS_STATEMENT Node = 23
	INPUT_ARRAY Node = 24
	INTERACTIVE_STATEMENT Node = 25
	MATRIX_ARRAY Node = 26
	MATRIX_BLOCK Node = 27
	MATRIX_VALUE Node = 28
	MULTILINE_STRING Node = 29
	NEW_LINE Node = 30
	NONEMPTY_STRING Node = 31
	NodeAliases Node = 32
	NodeArtifactsBlock Node = 33
	NodeBoolean Node = 34
	NodeCacheInputs Node = 35
	NodeCacheOutputDirectory Node = 36
	NodeCondition Node = 37
	NodeConditional Node = 38
	NodeConditionalParameter Node = 39
	NodeConditionalTarget Node = 40
	NodeConfirmKW Node = 41
	NodeDependencyOptions Node = 42
	NodeDependencyParameterName Node = 43
	NodeDependencyParameters Node = 44
	NodeDependsOnParameterRef Node = 45
	NodeDynamic Node = 46
	NodeDynamicArray Node = 47
	NodeEnvDeclaration Node = 48
	NodeEnvKey Node = 49
	NodeGlob Node = 50
	NodeGlobArguments Node = 51
	NodeGlobBaseDirectory Node = 52
	NodeGlobKwarg Node = 53
	NodeGlobKwargIdentifier Node = 54
	NodeHelpStatement Node = 55
	NodeHiddenStatement Node = 56
	NodeInputArray Node = 57
	NodeInteractiveStatement Node = 58
	NodeInterpolatedVariable Node = 59
	NodeInvokeTarget Node = 60
	NodeMatrixArray Node = 61
	NodeMatrixBlock Node = 62
	NodeMatrixIdentifier Node = 63
	NodeMultilineString Node = 64
	NodeNumber Node = 65
	NodeOptionalKW Node = 66
	NodeOutputArray Node = 67
	NodePath Node = 68
	NodePathArgs Node = 69
	NodeProgram Node = 70
	NodeRunStatement Node = 71
	NodeStringArray Node = 72
	NodeStringDollar Node = 73
	NodeStringEscape Node = 74
	NodeStringInterpolation Node = 75
	NodeStringLiteral Node = 76
	NodeStringText Node = 77
	NodeTarget Node = 78
	NodeTargetArray Node = 79
	NodeTargetBody Node = 80
	NodeTargetDependency Node = 81
	NodeTargetDepends Node = 82
	NodeTargetExecution Node = 83
	NodeTargetIdentifier Node = 84
	NodeTargetParameter Node = 85
	NodeTargetParameterIdentifier Node = 86
	NodeTargetParameterOptional Node = 87
	NodeTargetParams Node = 88
	NodeVariableArray Node = 89
	NodeVariableDeclaration Node = 90
	NodeVariableName Node = 91
	NodeVariableReference Node = 92
	NodeVariableValue Node = 93
	NodeVolatile Node = 94
	NodeWorkingDirectory Node = 95
	OUTPUT_ARRAY Node = 96
	OUTPUT_STATEMENT Node = 97
	OUTPUT_STATEMENT_VALUE Node = 98
	PATH Node = 99
	PATH_ARGS Node = 100
	PATH_ARRAY Node = 101
	PATH_ELEMENT Node = 102
	RUN Node = 103
	STRING_BODY Node = 104
	STRING_INTERPOLATION Node = 105
	STRING_LITERAL Node = 106
	TARGET Node = 107
	TARGET_ARRAY Node = 108
	TARGET_BODY Node = 109
	TARGET_DEPENDENCY Node = 110
	TARGET_EXECUTION Node = 111
	TARGET_PARAM Node = 112
	TARGET_PARAMS Node = 113
	TEXT_STRING Node = 114
	TRUE_OR_FALSE Node = 115
	VARIABLE_ARRAY Node = 116
	VARIABLE_STATEMENT Node = 117
	VARIABLE_VALUE Node = 118
	VAR_REF Node = 119
	VOLATILE_STATEMENT Node = 120
	WORK_DIR Node = 121
	gr_ARTIFACTS_STATEMENT Node = 122
	gr_DEFINES Node = 123
	gr_DEPENDENCY_PARAM_CONTENT Node = 124
	gr_DEPENDENCY_PARAM_VALUE Node = 125
	gr_DEP_EL Node = 126
	gr_DYNAMIC_VALUE Node = 127
	gr_EMPTY_STRING Node = 128
	gr_ENV_ASSIGNMENT Node = 129
	gr_ENV_VALUE Node = 130
	gr_EQUALS Node = 131
	gr_INPUTS_VALUE Node = 132
	gr_MATRIX_ARRAY_ELEMENT Node = 133
	gr_MATRIX_VALUE Node = 134
	gr_NEW_LINE Node = 135
	gr_NONEMPTY_STRING Node = 136
	gr_OUTPUT_VALUE Node = 137
	gr_PATH_ARRAY Node = 138
	gr_PATH_ARRAY_ELEMENT Node = 139
	gr_PATH_ELEMENT Node = 140
	gr_STRING_BODY Node = 141
	gr_TEXT_STRING Node = 142
	gr_TRUE_OR_FALSE Node = 143
	gr_VAR_REF Node = 144
)

var NodeNames = [...]string{
	"ALIASES_DECLARATION",
	"ARTIFACTS_BLOCK",
	"CONDITIONAL_BLOCK",
	"CONDITIONAL_TARGET",
	"DEFINES",
	"DEPENDENCY_OPTIONS",
	"DEPENDENCY_PARAMS",
	"DEPENDENCY_PARAM_CONTENT",
	"DEPENDENCY_PARAM_REF",
	"DEPENDS_ON",
	"DYNAMIC_ARRAY",
	"DYNAMIC_STATEMENT",
	"EMPTY_STRING",
	"ENV_DECLARATION",
	"EQUALS",
	"ERROR_NODE",
	"GLOB",
	"GLOB_ARGS",
	"GLOB_BASE_DIR",
	"GLOB_KWARG",
	"HELP_STATEMENT",
	"HIDDEN_STATEMENT",
	"INPUTS_STATEMENT",
	"INPUT_ARRAY",
	"INTERACTIVE_STATEMENT",
	"MATRIX_ARRAY",
	"MATRIX_BLOCK",
	"MATRIX_VALUE",
	"MULTILINE_STRING",
	"NEW_LINE",
	"NONEMPTY_STRING",
	"NodeAliases",
	"NodeArtifactsBlock",
	"NodeBoolean",
	"NodeCacheInputs",
	"NodeCacheOutputDirectory",
	"NodeCondition",
	"NodeConditional",
	"NodeConditionalParameter",
	"NodeConditionalTarget",
	"NodeConfirmKW",
	"NodeDependencyOptions",
	"NodeDependencyParameterName",
	"NodeDependencyParameters",
	"NodeDependsOnParameterRef",
	"NodeDynamic",
	"NodeDynamicArray",
	"NodeEnvDeclaration",
	"NodeEnvKey",
	"NodeGlob",
	"NodeGlobArguments",
	"NodeGlobBaseDirectory",
	"NodeGlobKwarg",
	"NodeGlobKwargIdentifier",
	"NodeHelpStatement",
	"NodeHiddenStatement",
	"NodeInputArray",
	"NodeInteractiveStatement",
	"NodeInterpolatedVariable",
	"NodeInvokeTarget",
	"NodeMatrixArray",
	"NodeMatrixBlock",
	"NodeMatrixIdentifier",
	"NodeMultilineString",
	"NodeNumber",
	"NodeOptionalKW",
	"NodeOutputArray",
	"NodePath",
	"NodePathArgs",
	"NodeProgram",
	"NodeRunStatement",
	"NodeStringArray",
	"NodeStringDollar",
	"NodeStringEscape",
	"NodeStringInterpolation",
	"NodeStringLiteral",
	"NodeStringText",
	"NodeTarget",
	"NodeTargetArray",
	"NodeTargetBody",
	"NodeTargetDependency",
	"NodeTargetDepends",
	"NodeTargetExecution",
	"NodeTargetIdentifier",
	"NodeTargetParameter",
	"NodeTargetParameterIdentifier",
	"NodeTargetParameterOptional",
	"NodeTargetParams",
	"NodeVariableArray",
	"NodeVariableDeclaration",
	"NodeVariableName",
	"NodeVariableReference",
	"NodeVariableValue",
	"NodeVolatile",
	"NodeWorkingDirectory",
	"OUTPUT_ARRAY",
	"OUTPUT_STATEMENT",
	"OUTPUT_STATEMENT_VALUE",
	"PATH",
	"PATH_ARGS",
	"PATH_ARRAY",
	"PATH_ELEMENT",
	"RUN",
	"STRING_BODY",
	"STRING_INTERPOLATION",
	"STRING_LITERAL",
	"TARGET",
	"TARGET_ARRAY",
	"TARGET_BODY",
	"TARGET_DEPENDENCY",
	"TARGET_EXECUTION",
	"TARGET_PARAM",
	"TARGET_PARAMS",
	"TEXT_STRING",
	"TRUE_OR_FALSE",
	"VARIABLE_ARRAY",
	"VARIABLE_STATEMENT",
	"VARIABLE_VALUE",
	"VAR_REF",
	"VOLATILE_STATEMENT",
	"WORK_DIR",
	"gr_ARTIFACTS_STATEMENT",
	"gr_DEFINES",
	"gr_DEPENDENCY_PARAM_CONTENT",
	"gr_DEPENDENCY_PARAM_VALUE",
	"gr_DEP_EL",
	"gr_DYNAMIC_VALUE",
	"gr_EMPTY_STRING",
	"gr_ENV_ASSIGNMENT",
	"gr_ENV_VALUE",
	"gr_EQUALS",
	"gr_INPUTS_VALUE",
	"gr_MATRIX_ARRAY_ELEMENT",
	"gr_MATRIX_VALUE",
	"gr_NEW_LINE",
	"gr_NONEMPTY_STRING",
	"gr_OUTPUT_VALUE",
	"gr_PATH_ARRAY",
	"gr_PATH_ARRAY_ELEMENT",
	"gr_PATH_ELEMENT",
	"gr_STRING_BODY",
	"gr_TEXT_STRING",
	"gr_TRUE_OR_FALSE",
	"gr_VAR_REF",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
