// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokBlockComment Token = 2
	TokBraceClose Token = 3
	TokBraceOpen Token = 4
	TokBracketClose Token = 5
	TokBracketOpen Token = 6
	TokComma Token = 7
	TokDollar Token = 8
	TokDot Token = 9
	TokEOF Token = 10
	TokEmptyString Token = 11
	TokEquals Token = 12
	TokIdentifier Token = 13
	TokInteger Token = 14
	TokInterpolationEnd Token = 15
	TokInterpolationStart Token = 16
	TokKWAdapter Token = 17
	TokKWAliases Token = 18
	TokKWArtifacts Token = 19
	TokKWCollect Token = 20
	TokKWCollectClosure Token = 21
	TokKWConfiguration Token = 22
	TokKWConfirm Token = 23
	TokKWDefined Token = 24
	TokKWDependsOn Token = 25
	TokKWDeps Token = 26
	TokKWDynamic Token = 27
	TokKWEntity Token = 28
	TokKWEnv Token = 29
	TokKWEquals Token = 30
	TokKWExclude Token = 31
	TokKWExport Token = 32
	TokKWFalse Token = 33
	TokKWGlob Token = 34
	TokKWGlobals Token = 35
	TokKWHelp Token = 36
	TokKWHidden Token = 37
	TokKWIn Token = 38
	TokKWInclude Token = 39
	TokKWInputs Token = 40
	TokKWInteractive Token = 41
	TokKWInterface Token = 42
	TokKWKeys Token = 43
	TokKWKind Token = 44
	TokKWLet Token = 45
	TokKWMatrix Token = 46
	TokKWNotDefined Token = 47
	TokKWNotEquals Token = 48
	TokKWOptional Token = 49
	TokKWOutputs Token = 50
	TokKWParam Token = 51
	TokKWParams Token = 52
	TokKWPath Token = 53
	TokKWRun Token = 54
	TokKWTarget Token = 55
	TokKWTrue Token = 56
	TokKWUsage Token = 57
	TokKWUse Token = 58
	TokKWVolatile Token = 59
	TokKWWhen Token = 60
	TokKWWorkingDir Token = 61
	TokKWWorkspace Token = 62
	TokLineComment Token = 63
	TokMultilineStringEnd Token = 64
	TokMultilineStringStart Token = 65
	TokMultilineStringText Token = 66
	TokNewLine Token = 67
	TokParenClose Token = 68
	TokParenOpen Token = 69
	TokQuestion Token = 70
	TokStringEnd Token = 71
	TokStringEscape Token = 72
	TokStringLiteral Token = 73
	TokStringStart Token = 74
	TokWhitespace Token = 75
)

var TokenNames = [...]string{
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokComma",
	"TokDollar",
	"TokDot",
	"TokEOF",
	"TokEmptyString",
	"TokEquals",
	"TokIdentifier",
	"TokInteger",
	"TokInterpolationEnd",
	"TokInterpolationStart",
	"TokKWAdapter",
	"TokKWAliases",
	"TokKWArtifacts",
	"TokKWCollect",
	"TokKWCollectClosure",
	"TokKWConfiguration",
	"TokKWConfirm",
	"TokKWDefined",
	"TokKWDependsOn",
	"TokKWDeps",
	"TokKWDynamic",
	"TokKWEntity",
	"TokKWEnv",
	"TokKWEquals",
	"TokKWExclude",
	"TokKWExport",
	"TokKWFalse",
	"TokKWGlob",
	"TokKWGlobals",
	"TokKWHelp",
	"TokKWHidden",
	"TokKWIn",
	"TokKWInclude",
	"TokKWInputs",
	"TokKWInteractive",
	"TokKWInterface",
	"TokKWKeys",
	"TokKWKind",
	"TokKWLet",
	"TokKWMatrix",
	"TokKWNotDefined",
	"TokKWNotEquals",
	"TokKWOptional",
	"TokKWOutputs",
	"TokKWParam",
	"TokKWParams",
	"TokKWPath",
	"TokKWRun",
	"TokKWTarget",
	"TokKWTrue",
	"TokKWUsage",
	"TokKWUse",
	"TokKWVolatile",
	"TokKWWhen",
	"TokKWWorkingDir",
	"TokKWWorkspace",
	"TokLineComment",
	"TokMultilineStringEnd",
	"TokMultilineStringStart",
	"TokMultilineStringText",
	"TokNewLine",
	"TokParenClose",
	"TokParenOpen",
	"TokQuestion",
	"TokStringEnd",
	"TokStringEscape",
	"TokStringLiteral",
	"TokStringStart",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	ADAPTER_BODY Node = 1
	ADAPTER_DECL Node = 2
	ADAPTER_ENV Node = 3
	ADAPTER_OUTPUTS Node = 4
	ADAPTER_PHASE Node = 5
	ADAPTER_PHASE_BODY Node = 6
	ADAPTER_PHASE_DEPENDS Node = 7
	ADAPTER_PHASE_DEPENDS_ARRAY Node = 8
	ALIASES_DECLARATION Node = 9
	ARTIFACTS_BLOCK Node = 10
	CONDITIONAL_BLOCK Node = 11
	CONDITIONAL_TARGET Node = 12
	CONFIGURATION_BODY Node = 13
	CONFIGURATION_DECL Node = 14
	CONFIGURATION_GLOBALS_BLOCK Node = 15
	DEFINES Node = 16
	DEPENDENCY_OPTIONS Node = 17
	DEPENDENCY_PARAMS Node = 18
	DEPENDENCY_PARAM_CONTENT Node = 19
	DEPENDENCY_PARAM_REF Node = 20
	DEPENDS_ON Node = 21
	DYNAMIC_ARRAY Node = 22
	DYNAMIC_STATEMENT Node = 23
	EMPTY_STRING Node = 24
	ENTITY Node = 25
	ENTITY_BODY Node = 26
	ENTITY_CONFIGURATION Node = 27
	ENTITY_CONFIGURATION_BODY Node = 28
	ENTITY_DEPENDENCY_OPTIONS Node = 29
	ENTITY_DEPS Node = 30
	ENTITY_INTERFACE Node = 31
	ENTITY_KIND Node = 32
	ENTITY_LABEL_DEPENDENCY Node = 33
	ENTITY_USAGE Node = 34
	ENTITY_USE Node = 35
	ENTITY_USE_OPTIONS Node = 36
	ENTITY_USE_OPTIONS_BODY Node = 37
	ENV_DECLARATION Node = 38
	EQUALS Node = 39
	ERROR_NODE Node = 40
	EXPORT_DECLARATION Node = 41
	GLOB Node = 42
	GLOB_ARGS Node = 43
	GLOB_BASE_DIR Node = 44
	GLOB_INCLUDE_KWARG Node = 45
	GLOB_KWARG Node = 46
	GLOB_NAMED_KWARG Node = 47
	HELP_STATEMENT Node = 48
	HIDDEN_STATEMENT Node = 49
	INPUTS_STATEMENT Node = 50
	INPUT_ARRAY Node = 51
	INTERACTIVE_STATEMENT Node = 52
	INTERFACE_BODY Node = 53
	INTERFACE_DECL Node = 54
	INTERFACE_KEYS Node = 55
	LABEL_REF Node = 56
	LET_BINDING Node = 57
	MATRIX_ARRAY Node = 58
	MATRIX_BLOCK Node = 59
	MATRIX_VALUE Node = 60
	MULTILINE_STRING Node = 61
	NEW_LINE Node = 62
	NONEMPTY_STRING Node = 63
	NodeAdapterBody Node = 64
	NodeAdapterDecl Node = 65
	NodeAdapterEnv Node = 66
	NodeAdapterName Node = 67
	NodeAdapterOutputs Node = 68
	NodeAdapterPhase Node = 69
	NodeAdapterPhaseBody Node = 70
	NodeAdapterPhaseDepends Node = 71
	NodeAdapterPhaseDependsArray Node = 72
	NodeAdapterPhaseDependsIdentifier Node = 73
	NodeAdapterPhaseDependsName Node = 74
	NodeAdapterPhaseName Node = 75
	NodeAliases Node = 76
	NodeArtifactsBlock Node = 77
	NodeBoolean Node = 78
	NodeCacheInputs Node = 79
	NodeCacheOutputDirectory Node = 80
	NodeCondition Node = 81
	NodeConditional Node = 82
	NodeConditionalParameter Node = 83
	NodeConditionalTarget Node = 84
	NodeConfigurationBody Node = 85
	NodeConfigurationDecl Node = 86
	NodeConfigurationGlobals Node = 87
	NodeConfigurationName Node = 88
	NodeConfirmKW Node = 89
	NodeDependencyOptions Node = 90
	NodeDependencyParameterName Node = 91
	NodeDependencyParameters Node = 92
	NodeDependsOnParameterRef Node = 93
	NodeDynamic Node = 94
	NodeDynamicArray Node = 95
	NodeEntity Node = 96
	NodeEntityAdapterName Node = 97
	NodeEntityBody Node = 98
	NodeEntityConfiguration Node = 99
	NodeEntityConfigurationBody Node = 100
	NodeEntityConfigurationName Node = 101
	NodeEntityDependencyConfiguration Node = 102
	NodeEntityDependencyOptions Node = 103
	NodeEntityDeps Node = 104
	NodeEntityInterface Node = 105
	NodeEntityInterfaceKey Node = 106
	NodeEntityKind Node = 107
	NodeEntityLabelDependency Node = 108
	NodeEntityName Node = 109
	NodeEntityUsage Node = 110
	NodeEntityUsageKey Node = 111
	NodeEntityUse Node = 112
	NodeEntityUseOptions Node = 113
	NodeEntityUseOptionsBody Node = 114
	NodeEnvDeclaration Node = 115
	NodeEnvKey Node = 116
	NodeExportDeclaration Node = 117
	NodeExportKey Node = 118
	NodeGlob Node = 119
	NodeGlobArguments Node = 120
	NodeGlobBaseDirectory Node = 121
	NodeGlobIncludeKwarg Node = 122
	NodeGlobKwarg Node = 123
	NodeGlobKwargIdentifier Node = 124
	NodeGlobNamedKwarg Node = 125
	NodeHelpStatement Node = 126
	NodeHiddenStatement Node = 127
	NodeInputArray Node = 128
	NodeInteractiveStatement Node = 129
	NodeInterfaceBody Node = 130
	NodeInterfaceDecl Node = 131
	NodeInterfaceKeys Node = 132
	NodeInterfaceName Node = 133
	NodeInterpolatedVariable Node = 134
	NodeInvokeTarget Node = 135
	NodeLabelRef Node = 136
	NodeLetBinding Node = 137
	NodeLetBindingName Node = 138
	NodeMatrixArray Node = 139
	NodeMatrixBlock Node = 140
	NodeMatrixIdentifier Node = 141
	NodeMultilineString Node = 142
	NodeNumber Node = 143
	NodeOptionalKW Node = 144
	NodeOutputArray Node = 145
	NodeParamValueArray Node = 146
	NodeParamValueParamName Node = 147
	NodeParamValueParamRef Node = 148
	NodePath Node = 149
	NodePathArgs Node = 150
	NodePathCallArgs Node = 151
	NodePathVarOrCall Node = 152
	NodePathVarOrCallName Node = 153
	NodeProgram Node = 154
	NodeRunAbsPathCall Node = 155
	NodeRunAbsPathCallName Node = 156
	NodeRunArray Node = 157
	NodeRunParameterName Node = 158
	NodeRunParameterRef Node = 159
	NodeRunPhaseOutputsMember Node = 160
	NodeRunPhaseOutputsSuffix Node = 161
	NodeRunStatement Node = 162
	NodeStringArray Node = 163
	NodeStringDollar Node = 164
	NodeStringEscape Node = 165
	NodeStringInterpolation Node = 166
	NodeStringListArray Node = 167
	NodeStringListCollectArgs Node = 168
	NodeStringListCollectCall Node = 169
	NodeStringListCollectClosureCall Node = 170
	NodeStringListCollectDepsParam Node = 171
	NodeStringListParamName Node = 172
	NodeStringListParamRef Node = 173
	NodeStringLiteral Node = 174
	NodeStringText Node = 175
	NodeTarget Node = 176
	NodeTargetBody Node = 177
	NodeTargetConfiguration Node = 178
	NodeTargetDependency Node = 179
	NodeTargetDepends Node = 180
	NodeTargetExecution Node = 181
	NodeTargetIdentifier Node = 182
	NodeTargetParameter Node = 183
	NodeTargetParameterIdentifier Node = 184
	NodeTargetParameterOptional Node = 185
	NodeTargetParams Node = 186
	NodeVariableArray Node = 187
	NodeVariableDeclaration Node = 188
	NodeVariableName Node = 189
	NodeVariableReference Node = 190
	NodeVariableValue Node = 191
	NodeVolatile Node = 192
	NodeWorkingDirectory Node = 193
	NodeWorkspace Node = 194
	NodeWorkspaceBody Node = 195
	NodeWorkspaceExclude Node = 196
	NodeWorkspaceGlobalAssignment Node = 197
	NodeWorkspaceGlobalKey Node = 198
	NodeWorkspaceGlobals Node = 199
	NodeWorkspaceGlobalsBody Node = 200
	OUTPUT_ARRAY Node = 201
	OUTPUT_STATEMENT Node = 202
	OUTPUT_STATEMENT_VALUE Node = 203
	PARAM_VALUE_ARRAY Node = 204
	PARAM_VALUE_PARAM_REF Node = 205
	PATH Node = 206
	PATH_ARGS Node = 207
	PATH_ARRAY Node = 208
	PATH_CALL_ARGS Node = 209
	PATH_ELEMENT Node = 210
	PATH_EXPR Node = 211
	PATH_VAR_OR_CALL Node = 212
	RUN Node = 213
	RUN_ABS_PATH_CALL Node = 214
	RUN_ARRAY Node = 215
	RUN_PARAM_REF Node = 216
	RUN_PHASE_OUTPUTS_SUFFIX Node = 217
	STRING_BODY Node = 218
	STRING_INTERPOLATION Node = 219
	STRING_LIST_ARRAY Node = 220
	STRING_LIST_COLLECT_ARGS Node = 221
	STRING_LIST_COLLECT_CALL Node = 222
	STRING_LIST_COLLECT_CLOSURE_CALL Node = 223
	STRING_LIST_PARAM_REF Node = 224
	STRING_LITERAL Node = 225
	TARGET Node = 226
	TARGET_BODY Node = 227
	TARGET_CONFIGURATION Node = 228
	TARGET_DEPENDENCY Node = 229
	TARGET_EXECUTION Node = 230
	TARGET_PARAM Node = 231
	TARGET_PARAMS Node = 232
	TEXT_STRING Node = 233
	TRUE_OR_FALSE Node = 234
	VARIABLE_ARRAY Node = 235
	VARIABLE_STATEMENT Node = 236
	VARIABLE_VALUE Node = 237
	VAR_REF Node = 238
	VOLATILE_STATEMENT Node = 239
	WORKSPACE_BLOCK Node = 240
	WORKSPACE_BODY Node = 241
	WORKSPACE_EXCLUDE Node = 242
	WORKSPACE_GLOBALS_BLOCK Node = 243
	WORKSPACE_GLOBALS_BODY Node = 244
	WORKSPACE_GLOBAL_ASSIGNMENT Node = 245
	WORK_DIR Node = 246
	gr_ARTIFACTS_STATEMENT Node = 247
	gr_DEFINES Node = 248
	gr_DEPENDENCY_PARAM_CONTENT Node = 249
	gr_DEPENDENCY_PARAM_VALUE Node = 250
	gr_DEP_EL Node = 251
	gr_DYNAMIC_VALUE Node = 252
	gr_EMPTY_STRING Node = 253
	gr_ENTITY_DEPS_ELEMENT Node = 254
	gr_ENTITY_INTERFACE_ASSIGNMENT Node = 255
	gr_ENTITY_USAGE_ASSIGNMENT Node = 256
	gr_ENV_ASSIGNMENT Node = 257
	gr_ENV_VALUE Node = 258
	gr_EQUALS Node = 259
	gr_EXPORT_ASSIGNMENT Node = 260
	gr_EXPORT_VALUE Node = 261
	gr_INPUTS_VALUE Node = 262
	gr_MATRIX_ARRAY_ELEMENT Node = 263
	gr_MATRIX_VALUE Node = 264
	gr_NEW_LINE Node = 265
	gr_NONEMPTY_STRING Node = 266
	gr_OUTPUT_VALUE Node = 267
	gr_PARAM_VALUE_ARRAY_ELEMENT Node = 268
	gr_PATH_ARRAY Node = 269
	gr_PATH_ARRAY_ELEMENT Node = 270
	gr_PATH_ELEMENT Node = 271
	gr_PATH_EXPR Node = 272
	gr_RUN_ARRAY_ELEMENT Node = 273
	gr_STRING_BODY Node = 274
	gr_STRING_LIST_ELEMENT Node = 275
	gr_TEXT_STRING Node = 276
	gr_TRUE_OR_FALSE Node = 277
	gr_VAR_REF Node = 278
)

var NodeNames = [...]string{
	"ADAPTER_BODY",
	"ADAPTER_DECL",
	"ADAPTER_ENV",
	"ADAPTER_OUTPUTS",
	"ADAPTER_PHASE",
	"ADAPTER_PHASE_BODY",
	"ADAPTER_PHASE_DEPENDS",
	"ADAPTER_PHASE_DEPENDS_ARRAY",
	"ALIASES_DECLARATION",
	"ARTIFACTS_BLOCK",
	"CONDITIONAL_BLOCK",
	"CONDITIONAL_TARGET",
	"CONFIGURATION_BODY",
	"CONFIGURATION_DECL",
	"CONFIGURATION_GLOBALS_BLOCK",
	"DEFINES",
	"DEPENDENCY_OPTIONS",
	"DEPENDENCY_PARAMS",
	"DEPENDENCY_PARAM_CONTENT",
	"DEPENDENCY_PARAM_REF",
	"DEPENDS_ON",
	"DYNAMIC_ARRAY",
	"DYNAMIC_STATEMENT",
	"EMPTY_STRING",
	"ENTITY",
	"ENTITY_BODY",
	"ENTITY_CONFIGURATION",
	"ENTITY_CONFIGURATION_BODY",
	"ENTITY_DEPENDENCY_OPTIONS",
	"ENTITY_DEPS",
	"ENTITY_INTERFACE",
	"ENTITY_KIND",
	"ENTITY_LABEL_DEPENDENCY",
	"ENTITY_USAGE",
	"ENTITY_USE",
	"ENTITY_USE_OPTIONS",
	"ENTITY_USE_OPTIONS_BODY",
	"ENV_DECLARATION",
	"EQUALS",
	"ERROR_NODE",
	"EXPORT_DECLARATION",
	"GLOB",
	"GLOB_ARGS",
	"GLOB_BASE_DIR",
	"GLOB_INCLUDE_KWARG",
	"GLOB_KWARG",
	"GLOB_NAMED_KWARG",
	"HELP_STATEMENT",
	"HIDDEN_STATEMENT",
	"INPUTS_STATEMENT",
	"INPUT_ARRAY",
	"INTERACTIVE_STATEMENT",
	"INTERFACE_BODY",
	"INTERFACE_DECL",
	"INTERFACE_KEYS",
	"LABEL_REF",
	"LET_BINDING",
	"MATRIX_ARRAY",
	"MATRIX_BLOCK",
	"MATRIX_VALUE",
	"MULTILINE_STRING",
	"NEW_LINE",
	"NONEMPTY_STRING",
	"NodeAdapterBody",
	"NodeAdapterDecl",
	"NodeAdapterEnv",
	"NodeAdapterName",
	"NodeAdapterOutputs",
	"NodeAdapterPhase",
	"NodeAdapterPhaseBody",
	"NodeAdapterPhaseDepends",
	"NodeAdapterPhaseDependsArray",
	"NodeAdapterPhaseDependsIdentifier",
	"NodeAdapterPhaseDependsName",
	"NodeAdapterPhaseName",
	"NodeAliases",
	"NodeArtifactsBlock",
	"NodeBoolean",
	"NodeCacheInputs",
	"NodeCacheOutputDirectory",
	"NodeCondition",
	"NodeConditional",
	"NodeConditionalParameter",
	"NodeConditionalTarget",
	"NodeConfigurationBody",
	"NodeConfigurationDecl",
	"NodeConfigurationGlobals",
	"NodeConfigurationName",
	"NodeConfirmKW",
	"NodeDependencyOptions",
	"NodeDependencyParameterName",
	"NodeDependencyParameters",
	"NodeDependsOnParameterRef",
	"NodeDynamic",
	"NodeDynamicArray",
	"NodeEntity",
	"NodeEntityAdapterName",
	"NodeEntityBody",
	"NodeEntityConfiguration",
	"NodeEntityConfigurationBody",
	"NodeEntityConfigurationName",
	"NodeEntityDependencyConfiguration",
	"NodeEntityDependencyOptions",
	"NodeEntityDeps",
	"NodeEntityInterface",
	"NodeEntityInterfaceKey",
	"NodeEntityKind",
	"NodeEntityLabelDependency",
	"NodeEntityName",
	"NodeEntityUsage",
	"NodeEntityUsageKey",
	"NodeEntityUse",
	"NodeEntityUseOptions",
	"NodeEntityUseOptionsBody",
	"NodeEnvDeclaration",
	"NodeEnvKey",
	"NodeExportDeclaration",
	"NodeExportKey",
	"NodeGlob",
	"NodeGlobArguments",
	"NodeGlobBaseDirectory",
	"NodeGlobIncludeKwarg",
	"NodeGlobKwarg",
	"NodeGlobKwargIdentifier",
	"NodeGlobNamedKwarg",
	"NodeHelpStatement",
	"NodeHiddenStatement",
	"NodeInputArray",
	"NodeInteractiveStatement",
	"NodeInterfaceBody",
	"NodeInterfaceDecl",
	"NodeInterfaceKeys",
	"NodeInterfaceName",
	"NodeInterpolatedVariable",
	"NodeInvokeTarget",
	"NodeLabelRef",
	"NodeLetBinding",
	"NodeLetBindingName",
	"NodeMatrixArray",
	"NodeMatrixBlock",
	"NodeMatrixIdentifier",
	"NodeMultilineString",
	"NodeNumber",
	"NodeOptionalKW",
	"NodeOutputArray",
	"NodeParamValueArray",
	"NodeParamValueParamName",
	"NodeParamValueParamRef",
	"NodePath",
	"NodePathArgs",
	"NodePathCallArgs",
	"NodePathVarOrCall",
	"NodePathVarOrCallName",
	"NodeProgram",
	"NodeRunAbsPathCall",
	"NodeRunAbsPathCallName",
	"NodeRunArray",
	"NodeRunParameterName",
	"NodeRunParameterRef",
	"NodeRunPhaseOutputsMember",
	"NodeRunPhaseOutputsSuffix",
	"NodeRunStatement",
	"NodeStringArray",
	"NodeStringDollar",
	"NodeStringEscape",
	"NodeStringInterpolation",
	"NodeStringListArray",
	"NodeStringListCollectArgs",
	"NodeStringListCollectCall",
	"NodeStringListCollectClosureCall",
	"NodeStringListCollectDepsParam",
	"NodeStringListParamName",
	"NodeStringListParamRef",
	"NodeStringLiteral",
	"NodeStringText",
	"NodeTarget",
	"NodeTargetBody",
	"NodeTargetConfiguration",
	"NodeTargetDependency",
	"NodeTargetDepends",
	"NodeTargetExecution",
	"NodeTargetIdentifier",
	"NodeTargetParameter",
	"NodeTargetParameterIdentifier",
	"NodeTargetParameterOptional",
	"NodeTargetParams",
	"NodeVariableArray",
	"NodeVariableDeclaration",
	"NodeVariableName",
	"NodeVariableReference",
	"NodeVariableValue",
	"NodeVolatile",
	"NodeWorkingDirectory",
	"NodeWorkspace",
	"NodeWorkspaceBody",
	"NodeWorkspaceExclude",
	"NodeWorkspaceGlobalAssignment",
	"NodeWorkspaceGlobalKey",
	"NodeWorkspaceGlobals",
	"NodeWorkspaceGlobalsBody",
	"OUTPUT_ARRAY",
	"OUTPUT_STATEMENT",
	"OUTPUT_STATEMENT_VALUE",
	"PARAM_VALUE_ARRAY",
	"PARAM_VALUE_PARAM_REF",
	"PATH",
	"PATH_ARGS",
	"PATH_ARRAY",
	"PATH_CALL_ARGS",
	"PATH_ELEMENT",
	"PATH_EXPR",
	"PATH_VAR_OR_CALL",
	"RUN",
	"RUN_ABS_PATH_CALL",
	"RUN_ARRAY",
	"RUN_PARAM_REF",
	"RUN_PHASE_OUTPUTS_SUFFIX",
	"STRING_BODY",
	"STRING_INTERPOLATION",
	"STRING_LIST_ARRAY",
	"STRING_LIST_COLLECT_ARGS",
	"STRING_LIST_COLLECT_CALL",
	"STRING_LIST_COLLECT_CLOSURE_CALL",
	"STRING_LIST_PARAM_REF",
	"STRING_LITERAL",
	"TARGET",
	"TARGET_BODY",
	"TARGET_CONFIGURATION",
	"TARGET_DEPENDENCY",
	"TARGET_EXECUTION",
	"TARGET_PARAM",
	"TARGET_PARAMS",
	"TEXT_STRING",
	"TRUE_OR_FALSE",
	"VARIABLE_ARRAY",
	"VARIABLE_STATEMENT",
	"VARIABLE_VALUE",
	"VAR_REF",
	"VOLATILE_STATEMENT",
	"WORKSPACE_BLOCK",
	"WORKSPACE_BODY",
	"WORKSPACE_EXCLUDE",
	"WORKSPACE_GLOBALS_BLOCK",
	"WORKSPACE_GLOBALS_BODY",
	"WORKSPACE_GLOBAL_ASSIGNMENT",
	"WORK_DIR",
	"gr_ARTIFACTS_STATEMENT",
	"gr_DEFINES",
	"gr_DEPENDENCY_PARAM_CONTENT",
	"gr_DEPENDENCY_PARAM_VALUE",
	"gr_DEP_EL",
	"gr_DYNAMIC_VALUE",
	"gr_EMPTY_STRING",
	"gr_ENTITY_DEPS_ELEMENT",
	"gr_ENTITY_INTERFACE_ASSIGNMENT",
	"gr_ENTITY_USAGE_ASSIGNMENT",
	"gr_ENV_ASSIGNMENT",
	"gr_ENV_VALUE",
	"gr_EQUALS",
	"gr_EXPORT_ASSIGNMENT",
	"gr_EXPORT_VALUE",
	"gr_INPUTS_VALUE",
	"gr_MATRIX_ARRAY_ELEMENT",
	"gr_MATRIX_VALUE",
	"gr_NEW_LINE",
	"gr_NONEMPTY_STRING",
	"gr_OUTPUT_VALUE",
	"gr_PARAM_VALUE_ARRAY_ELEMENT",
	"gr_PATH_ARRAY",
	"gr_PATH_ARRAY_ELEMENT",
	"gr_PATH_ELEMENT",
	"gr_PATH_EXPR",
	"gr_RUN_ARRAY_ELEMENT",
	"gr_STRING_BODY",
	"gr_STRING_LIST_ELEMENT",
	"gr_TEXT_STRING",
	"gr_TRUE_OR_FALSE",
	"gr_VAR_REF",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
