// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokBlockComment Token = 2
	TokBraceClose Token = 3
	TokBraceOpen Token = 4
	TokBracketClose Token = 5
	TokBracketOpen Token = 6
	TokComma Token = 7
	TokDollar Token = 8
	TokEOF Token = 9
	TokEquals Token = 10
	TokIdentifier Token = 11
	TokInteger Token = 12
	TokInterpolationEnd Token = 13
	TokInterpolationStart Token = 14
	TokKWAliases Token = 15
	TokKWArtifacts Token = 16
	TokKWConfirm Token = 17
	TokKWDefined Token = 18
	TokKWDependsOn Token = 19
	TokKWEnv Token = 20
	TokKWEquals Token = 21
	TokKWFalse Token = 22
	TokKWGlob Token = 23
	TokKWHelp Token = 24
	TokKWIn Token = 25
	TokKWInputs Token = 26
	TokKWMatrix Token = 27
	TokKWNotDefined Token = 28
	TokKWNotEquals Token = 29
	TokKWOptional Token = 30
	TokKWOutputs Token = 31
	TokKWParams Token = 32
	TokKWPath Token = 33
	TokKWRun Token = 34
	TokKWTarget Token = 35
	TokKWTrue Token = 36
	TokKWVolatile Token = 37
	TokKWWhen Token = 38
	TokKWWorkingDir Token = 39
	TokLineComment Token = 40
	TokNewLine Token = 41
	TokParenClose Token = 42
	TokParenOpen Token = 43
	TokQuestion Token = 44
	TokStringEnd Token = 45
	TokStringEscape Token = 46
	TokStringLiteral Token = 47
	TokStringStart Token = 48
	TokWhitespace Token = 49
)

var TokenNames = [...]string{
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokComma",
	"TokDollar",
	"TokEOF",
	"TokEquals",
	"TokIdentifier",
	"TokInteger",
	"TokInterpolationEnd",
	"TokInterpolationStart",
	"TokKWAliases",
	"TokKWArtifacts",
	"TokKWConfirm",
	"TokKWDefined",
	"TokKWDependsOn",
	"TokKWEnv",
	"TokKWEquals",
	"TokKWFalse",
	"TokKWGlob",
	"TokKWHelp",
	"TokKWIn",
	"TokKWInputs",
	"TokKWMatrix",
	"TokKWNotDefined",
	"TokKWNotEquals",
	"TokKWOptional",
	"TokKWOutputs",
	"TokKWParams",
	"TokKWPath",
	"TokKWRun",
	"TokKWTarget",
	"TokKWTrue",
	"TokKWVolatile",
	"TokKWWhen",
	"TokKWWorkingDir",
	"TokLineComment",
	"TokNewLine",
	"TokParenClose",
	"TokParenOpen",
	"TokQuestion",
	"TokStringEnd",
	"TokStringEscape",
	"TokStringLiteral",
	"TokStringStart",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	ALIASES_DECLARATION Node = 1
	ARTIFACTS_BLOCK Node = 2
	CONDITIONAL_BLOCK Node = 3
	CONDITIONAL_TARGET Node = 4
	DEFINES Node = 5
	DEPENDENCY_OPTIONS Node = 6
	DEPENDENCY_PARAMS Node = 7
	DEPENDENCY_PARAM_CONTENT Node = 8
	DEPENDS_ON Node = 9
	ENV_DECLARATION Node = 10
	EQUALS Node = 11
	ERROR_NODE Node = 12
	GLOB Node = 13
	GLOB_ARGS Node = 14
	GLOB_BASE_DIR Node = 15
	GLOB_KWARG Node = 16
	HELP_STATEMENT Node = 17
	INPUTS_STATEMENT Node = 18
	INPUT_ARRAY Node = 19
	MATRIX_ARRAY Node = 20
	MATRIX_BLOCK Node = 21
	MATRIX_VALUE Node = 22
	NEW_LINE Node = 23
	NodeAliases Node = 24
	NodeArtifactsBlock Node = 25
	NodeBoolean Node = 26
	NodeCacheInputs Node = 27
	NodeCacheOutputDirectory Node = 28
	NodeCondition Node = 29
	NodeConditional Node = 30
	NodeConditionalParameter Node = 31
	NodeConditionalTarget Node = 32
	NodeConfirmKW Node = 33
	NodeDependencyOptions Node = 34
	NodeDependencyParameterName Node = 35
	NodeDependencyParameters Node = 36
	NodeEnvDeclaration Node = 37
	NodeEnvKey Node = 38
	NodeGlob Node = 39
	NodeGlobArguments Node = 40
	NodeGlobBaseDirectory Node = 41
	NodeGlobKwarg Node = 42
	NodeGlobKwargIdentifier Node = 43
	NodeHelpStatement Node = 44
	NodeInputArray Node = 45
	NodeInterpolatedVariable Node = 46
	NodeInvokeTarget Node = 47
	NodeMatrixArray Node = 48
	NodeMatrixBlock Node = 49
	NodeMatrixIdentifier Node = 50
	NodeNumber Node = 51
	NodeOptionalKW Node = 52
	NodeOutputArray Node = 53
	NodePath Node = 54
	NodePathArgs Node = 55
	NodeProgram Node = 56
	NodeRunStatement Node = 57
	NodeStringArray Node = 58
	NodeStringDollar Node = 59
	NodeStringEscape Node = 60
	NodeStringInterpolation Node = 61
	NodeStringLiteral Node = 62
	NodeStringText Node = 63
	NodeTarget Node = 64
	NodeTargetBody Node = 65
	NodeTargetDependency Node = 66
	NodeTargetDepends Node = 67
	NodeTargetExecution Node = 68
	NodeTargetIdentifier Node = 69
	NodeTargetParameter Node = 70
	NodeTargetParameterIdentifier Node = 71
	NodeTargetParameterOptional Node = 72
	NodeTargetParams Node = 73
	NodeVariableDeclaration Node = 74
	NodeVariableName Node = 75
	NodeVariableReference Node = 76
	NodeVariableValue Node = 77
	NodeVolatile Node = 78
	NodeWorkingDirectory Node = 79
	OUTPUT_ARRAY Node = 80
	OUTPUT_STATEMENT Node = 81
	OUTPUT_STATEMENT_VALUE Node = 82
	PATH Node = 83
	PATH_ARGS Node = 84
	PATH_ELEMENT Node = 85
	RUN Node = 86
	STRING_INTERPOLATION Node = 87
	STRING_LITERAL Node = 88
	TARGET Node = 89
	TARGET_BODY Node = 90
	TARGET_DEPENDENCY Node = 91
	TARGET_EXECUTION Node = 92
	TARGET_PARAM Node = 93
	TARGET_PARAMS Node = 94
	TRUE_OR_FALSE Node = 95
	VARIABLE_STATEMENT Node = 96
	VARIABLE_TARGET Node = 97
	VAR_REF Node = 98
	VOLATILE_STATEMENT Node = 99
	WORK_DIR Node = 100
	gr_ARTIFACTS_STATEMENT Node = 101
	gr_DEFINES Node = 102
	gr_DEPENDENCY_PARAM_CONTENT Node = 103
	gr_DEPENDENCY_PARAM_VALUE Node = 104
	gr_DEP_EL Node = 105
	gr_ENV_ASSIGNMENT Node = 106
	gr_ENV_VALUE Node = 107
	gr_EQUALS Node = 108
	gr_INPUTS_VALUE Node = 109
	gr_INPUT_ARRAY_ELEMENT Node = 110
	gr_MATRIX_ARRAY_ELEMENT Node = 111
	gr_MATRIX_VALUE Node = 112
	gr_NEW_LINE Node = 113
	gr_OUTPUT_ARRAY_ELEMENT Node = 114
	gr_OUTPUT_VALUE Node = 115
	gr_PATH_ELEMENT Node = 116
	gr_TRUE_OR_FALSE Node = 117
	gr_VAR_REF Node = 118
)

var NodeNames = [...]string{
	"ALIASES_DECLARATION",
	"ARTIFACTS_BLOCK",
	"CONDITIONAL_BLOCK",
	"CONDITIONAL_TARGET",
	"DEFINES",
	"DEPENDENCY_OPTIONS",
	"DEPENDENCY_PARAMS",
	"DEPENDENCY_PARAM_CONTENT",
	"DEPENDS_ON",
	"ENV_DECLARATION",
	"EQUALS",
	"ERROR_NODE",
	"GLOB",
	"GLOB_ARGS",
	"GLOB_BASE_DIR",
	"GLOB_KWARG",
	"HELP_STATEMENT",
	"INPUTS_STATEMENT",
	"INPUT_ARRAY",
	"MATRIX_ARRAY",
	"MATRIX_BLOCK",
	"MATRIX_VALUE",
	"NEW_LINE",
	"NodeAliases",
	"NodeArtifactsBlock",
	"NodeBoolean",
	"NodeCacheInputs",
	"NodeCacheOutputDirectory",
	"NodeCondition",
	"NodeConditional",
	"NodeConditionalParameter",
	"NodeConditionalTarget",
	"NodeConfirmKW",
	"NodeDependencyOptions",
	"NodeDependencyParameterName",
	"NodeDependencyParameters",
	"NodeEnvDeclaration",
	"NodeEnvKey",
	"NodeGlob",
	"NodeGlobArguments",
	"NodeGlobBaseDirectory",
	"NodeGlobKwarg",
	"NodeGlobKwargIdentifier",
	"NodeHelpStatement",
	"NodeInputArray",
	"NodeInterpolatedVariable",
	"NodeInvokeTarget",
	"NodeMatrixArray",
	"NodeMatrixBlock",
	"NodeMatrixIdentifier",
	"NodeNumber",
	"NodeOptionalKW",
	"NodeOutputArray",
	"NodePath",
	"NodePathArgs",
	"NodeProgram",
	"NodeRunStatement",
	"NodeStringArray",
	"NodeStringDollar",
	"NodeStringEscape",
	"NodeStringInterpolation",
	"NodeStringLiteral",
	"NodeStringText",
	"NodeTarget",
	"NodeTargetBody",
	"NodeTargetDependency",
	"NodeTargetDepends",
	"NodeTargetExecution",
	"NodeTargetIdentifier",
	"NodeTargetParameter",
	"NodeTargetParameterIdentifier",
	"NodeTargetParameterOptional",
	"NodeTargetParams",
	"NodeVariableDeclaration",
	"NodeVariableName",
	"NodeVariableReference",
	"NodeVariableValue",
	"NodeVolatile",
	"NodeWorkingDirectory",
	"OUTPUT_ARRAY",
	"OUTPUT_STATEMENT",
	"OUTPUT_STATEMENT_VALUE",
	"PATH",
	"PATH_ARGS",
	"PATH_ELEMENT",
	"RUN",
	"STRING_INTERPOLATION",
	"STRING_LITERAL",
	"TARGET",
	"TARGET_BODY",
	"TARGET_DEPENDENCY",
	"TARGET_EXECUTION",
	"TARGET_PARAM",
	"TARGET_PARAMS",
	"TRUE_OR_FALSE",
	"VARIABLE_STATEMENT",
	"VARIABLE_TARGET",
	"VAR_REF",
	"VOLATILE_STATEMENT",
	"WORK_DIR",
	"gr_ARTIFACTS_STATEMENT",
	"gr_DEFINES",
	"gr_DEPENDENCY_PARAM_CONTENT",
	"gr_DEPENDENCY_PARAM_VALUE",
	"gr_DEP_EL",
	"gr_ENV_ASSIGNMENT",
	"gr_ENV_VALUE",
	"gr_EQUALS",
	"gr_INPUTS_VALUE",
	"gr_INPUT_ARRAY_ELEMENT",
	"gr_MATRIX_ARRAY_ELEMENT",
	"gr_MATRIX_VALUE",
	"gr_NEW_LINE",
	"gr_OUTPUT_ARRAY_ELEMENT",
	"gr_OUTPUT_VALUE",
	"gr_PATH_ELEMENT",
	"gr_TRUE_OR_FALSE",
	"gr_VAR_REF",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
