// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokArrow Token = 2
	TokAt Token = 3
	TokBlockComment Token = 4
	TokBraceClose Token = 5
	TokBraceOpen Token = 6
	TokBracketClose Token = 7
	TokBracketOpen Token = 8
	TokColon Token = 9
	TokComma Token = 10
	TokDollar Token = 11
	TokDot Token = 12
	TokEOF Token = 13
	TokEquals Token = 14
	TokFloat Token = 15
	TokHexColor Token = 16
	TokHue Token = 17
	TokIdentifier Token = 18
	TokInteger Token = 19
	TokKWAction Token = 20
	TokKWAdapter Token = 21
	TokKWAs Token = 22
	TokKWBackground Token = 23
	TokKWBaseLine Token = 24
	TokKWBorder Token = 25
	TokKWColor Token = 26
	TokKWColorSet Token = 27
	TokKWConfiguration Token = 28
	TokKWCoreConditions Token = 29
	TokKWDescription Token = 30
	TokKWDropSoundEnabled Token = 31
	TokKWEffectColor Token = 32
	TokKWEffectTemporary Token = 33
	TokKWExport Token = 34
	TokKWExtends Token = 35
	TokKWFalse Token = 36
	TokKWFontSize Token = 37
	TokKWFunc Token = 38
	TokKWHSL Token = 39
	TokKWHSLA Token = 40
	TokKWHSV Token = 41
	TokKWHSVA Token = 42
	TokKWHide Token = 43
	TokKWImplements Token = 44
	TokKWImport Token = 45
	TokKWInclude Token = 46
	TokKWInherit Token = 47
	TokKWMinimap Token = 48
	TokKWModule Token = 49
	TokKWOnHide Token = 50
	TokKWOnShow Token = 51
	TokKWOverride Token = 52
	TokKWPositional Token = 53
	TokKWPrivate Token = 54
	TokKWRGB Token = 55
	TokKWRGBA Token = 56
	TokKWRule Token = 57
	TokKWRuleset Token = 58
	TokKWScope Token = 59
	TokKWShape Token = 60
	TokKWShow Token = 61
	TokKWSize Token = 62
	TokKWSound Token = 63
	TokKWSoundID Token = 64
	TokKWSoundPath Token = 65
	TokKWSoundVolume Token = 66
	TokKWStyle Token = 67
	TokKWTemplate Token = 68
	TokKWTextColor Token = 69
	TokKWTheme Token = 70
	TokKWThemeSchema Token = 71
	TokKWTrue Token = 72
	TokKWVariants Token = 73
	TokKWVersion Token = 74
	TokKWWhen Token = 75
	TokKWWith Token = 76
	TokLightness Token = 77
	TokLineComment Token = 78
	TokOpEq Token = 79
	TokOpGt Token = 80
	TokOpGte Token = 81
	TokOpLt Token = 82
	TokOpLte Token = 83
	TokOpNeq Token = 84
	TokParenClose Token = 85
	TokParenOpen Token = 86
	TokPercentage Token = 87
	TokRGBAlpha Token = 88
	TokRGBBlue Token = 89
	TokRGBGreen Token = 90
	TokRGBRed Token = 91
	TokSaturation Token = 92
	TokSemi Token = 93
	TokStringLiteral Token = 94
	TokValue Token = 95
	TokVersionIndicator Token = 96
	TokWhitespace Token = 97
)

var TokenNames = [...]string{
	"TokArrow",
	"TokAt",
	"TokBlockComment",
	"TokBraceClose",
	"TokBraceOpen",
	"TokBracketClose",
	"TokBracketOpen",
	"TokColon",
	"TokComma",
	"TokDollar",
	"TokDot",
	"TokEOF",
	"TokEquals",
	"TokFloat",
	"TokHexColor",
	"TokHue",
	"TokIdentifier",
	"TokInteger",
	"TokKWAction",
	"TokKWAdapter",
	"TokKWAs",
	"TokKWBackground",
	"TokKWBaseLine",
	"TokKWBorder",
	"TokKWColor",
	"TokKWColorSet",
	"TokKWConfiguration",
	"TokKWCoreConditions",
	"TokKWDescription",
	"TokKWDropSoundEnabled",
	"TokKWEffectColor",
	"TokKWEffectTemporary",
	"TokKWExport",
	"TokKWExtends",
	"TokKWFalse",
	"TokKWFontSize",
	"TokKWFunc",
	"TokKWHSL",
	"TokKWHSLA",
	"TokKWHSV",
	"TokKWHSVA",
	"TokKWHide",
	"TokKWImplements",
	"TokKWImport",
	"TokKWInclude",
	"TokKWInherit",
	"TokKWMinimap",
	"TokKWModule",
	"TokKWOnHide",
	"TokKWOnShow",
	"TokKWOverride",
	"TokKWPositional",
	"TokKWPrivate",
	"TokKWRGB",
	"TokKWRGBA",
	"TokKWRule",
	"TokKWRuleset",
	"TokKWScope",
	"TokKWShape",
	"TokKWShow",
	"TokKWSize",
	"TokKWSound",
	"TokKWSoundID",
	"TokKWSoundPath",
	"TokKWSoundVolume",
	"TokKWStyle",
	"TokKWTemplate",
	"TokKWTextColor",
	"TokKWTheme",
	"TokKWThemeSchema",
	"TokKWTrue",
	"TokKWVariants",
	"TokKWVersion",
	"TokKWWhen",
	"TokKWWith",
	"TokLightness",
	"TokLineComment",
	"TokOpEq",
	"TokOpGt",
	"TokOpGte",
	"TokOpLt",
	"TokOpLte",
	"TokOpNeq",
	"TokParenClose",
	"TokParenOpen",
	"TokPercentage",
	"TokRGBAlpha",
	"TokRGBBlue",
	"TokRGBGreen",
	"TokRGBRed",
	"TokSaturation",
	"TokSemi",
	"TokStringLiteral",
	"TokValue",
	"TokVersionIndicator",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	ACTION_DEF Node = 1
	ADAPTER_BODY Node = 2
	ADAPTER_DEF Node = 3
	BACKGROUND Node = 4
	BASELINE_BLOCK Node = 5
	BASELINE_PROPERTY Node = 6
	BORDER Node = 7
	COLORSET Node = 8
	COLORSET_ITEM Node = 9
	COLORSET_ITEM_LIST Node = 10
	COLOR_CONFIG Node = 11
	COLOR_OVERRIDE Node = 12
	COLOR_REF Node = 13
	CONDITION_EXPR Node = 14
	CONDITION_LEFT Node = 15
	CONDITION_OPERATOR Node = 16
	CONDITION_RIGHT Node = 17
	CONFIGURATION Node = 18
	CONFIGURATION_ASSIGNMENT Node = 19
	CONFIGURATION_ASSIGNMENT_VALUE Node = 20
	CONFIGURATION_BODY Node = 21
	CORE_CONDITIONS Node = 22
	CORE_CONDITION_STMT Node = 23
	DESCRIPTION_STMT Node = 24
	EFFECT Node = 25
	ENGINE_DIRECTIVE Node = 26
	ENTITY_REF_WRAP Node = 27
	ERROR_NODE Node = 28
	EXTEND_SEQUENCE Node = 29
	FUNCTION Node = 30
	FUNCTION_BODY Node = 31
	FUNCTION_SIGNATURE Node = 32
	HEX_LITERAL Node = 33
	HSLA_LITERAL Node = 34
	HSL_LITERAL Node = 35
	HSVA_LITERAL Node = 36
	HSV_LITERAL Node = 37
	HUE_SHORTHAND Node = 38
	IMPLEMENT_SEQUENCE Node = 39
	IMPORT_STMT Node = 40
	INCLUDE_STMT Node = 41
	INHERIT_DEF Node = 42
	MAIN_BLOCK Node = 43
	MAIN_BLOCK_LIST Node = 44
	MINIMAP Node = 45
	MINIMAP_CONFIGURATION Node = 46
	MINIMAP_CONFIGURATION_LIST Node = 47
	MODULE_PATH Node = 48
	MODULE_STATEMENT Node = 49
	NodeActionDef Node = 50
	NodeActionType Node = 51
	NodeAdapter Node = 52
	NodeAlpha Node = 53
	NodeArgumentName Node = 54
	NodeArgumentType Node = 55
	NodeAssignTarget Node = 56
	NodeAssignmentValue Node = 57
	NodeBackground Node = 58
	NodeBaselineBlock Node = 59
	NodeBooleanLiteral Node = 60
	NodeBorder Node = 61
	NodeColorKey Node = 62
	NodeColorKeyReference Node = 63
	NodeColorOverride Node = 64
	NodeColorReference Node = 65
	NodeColorSet Node = 66
	NodeColorSetEntry Node = 67
	NodeColorSetName Node = 68
	NodeColorSetReference Node = 69
	NodeConditionExpr Node = 70
	NodeConditionTarget Node = 71
	NodeConditionValue Node = 72
	NodeConfiguration Node = 73
	NodeConfigurationEntry Node = 74
	NodeConfigurationKey Node = 75
	NodeConfigurationValue Node = 76
	NodeCoreConditions Node = 77
	NodeEffect Node = 78
	NodeEffectColor Node = 79
	NodeEffectTemporary Node = 80
	NodeEngineDirective Node = 81
	NodeExportKeyword Node = 82
	NodeExtends Node = 83
	NodeFunction Node = 84
	NodeFunctionArgument Node = 85
	NodeFunctionName Node = 86
	NodeFunctionSignature Node = 87
	NodeHexColor Node = 88
	NodeHue Node = 89
	NodeIdentifier Node = 90
	NodeImplements Node = 91
	NodeImport Node = 92
	NodeIncludeRuleset Node = 93
	NodeInheritDef Node = 94
	NodeInheritTarget Node = 95
	NodeIntLiteral Node = 96
	NodeLightness Node = 97
	NodeMainBlock Node = 98
	NodeMinimap Node = 99
	NodeMinimapColor Node = 100
	NodeMinimapShape Node = 101
	NodeMinimapSize Node = 102
	NodeModuleAlias Node = 103
	NodeModulePath Node = 104
	NodeOnHide Node = 105
	NodeOnShow Node = 106
	NodeOp Node = 107
	NodeOriginalSchemaKey Node = 108
	NodeOriginalSchemaReference Node = 109
	NodeOverride Node = 110
	NodePathSegment Node = 111
	NodePrivateKeyword Node = 112
	NodeProgram Node = 113
	NodeRGBAlpha Node = 114
	NodeRGBBlue Node = 115
	NodeRGBGreen Node = 116
	NodeRGBRed Node = 117
	NodeReferenceSegment Node = 118
	NodeRule Node = 119
	NodeRuleBlock Node = 120
	NodeRuleName Node = 121
	NodeRules Node = 122
	NodeRuleset Node = 123
	NodeRulesetDescription Node = 124
	NodeRulesetName Node = 125
	NodeRulesetOverride Node = 126
	NodeRulesetOverrideEntry Node = 127
	NodeRulesetOverrideKey Node = 128
	NodeRulesetOverrideTarget Node = 129
	NodeRulesetReference Node = 130
	NodeRulesetReferenceSegment Node = 131
	NodeSaturation Node = 132
	NodeSchemaKeyAdapter Node = 133
	NodeSchemaUsageTarget Node = 134
	NodeScopeAssignment Node = 135
	NodeScopeBlock Node = 136
	NodeSound Node = 137
	NodeSoundEnabled Node = 138
	NodeSoundID Node = 139
	NodeSoundPath Node = 140
	NodeSoundPositional Node = 141
	NodeSoundVolume Node = 142
	NodeStringArray Node = 143
	NodeStringLiteral Node = 144
	NodeStyleDef Node = 145
	NodeStyleKey Node = 146
	NodeStyleKeyRef Node = 147
	NodeStyleRef Node = 148
	NodeTargetSchemaKey Node = 149
	NodeTargetSchemaReference Node = 150
	NodeTemplate Node = 151
	NodeTemplateArguments Node = 152
	NodeTemplateName Node = 153
	NodeTemplateReferenceTarget Node = 154
	NodeTemplateUsage Node = 155
	NodeTextColor Node = 156
	NodeTextSize Node = 157
	NodeTheme Node = 158
	NodeThemeName Node = 159
	NodeThemeReference Node = 160
	NodeThemeSchema Node = 161
	NodeThemeSchemaName Node = 162
	NodeThemeSchemaReference Node = 163
	NodeThemeStyle Node = 164
	NodeThemeStyleName Node = 165
	NodeValue Node = 166
	NodeVariableName Node = 167
	NodeVariableRef Node = 168
	NodeVariantCondition Node = 169
	NodeVariantsBlock Node = 170
	NodeVersionIndicator Node = 171
	ON_HIDE_ACTION Node = 172
	ON_SHOW_ACTION Node = 173
	ORIGINAL_SCHEMA_REF Node = 174
	RGBA_LITERAL Node = 175
	RGB_LITERAL Node = 176
	RGB_SHORTHAND Node = 177
	RULE Node = 178
	RULES Node = 179
	RULESET Node = 180
	RULESET_BODY Node = 181
	RULESET_OVERRIDE Node = 182
	RULESET_OVERRIDE_STMT Node = 183
	RULESET_OVERRIDE_TARGET Node = 184
	RULESET_REFERENCE Node = 185
	RULE_BLOCK Node = 186
	RULE_BODY Node = 187
	RULE_PROPERTY Node = 188
	SCHEMA_KEY_CONVERT_STMT Node = 189
	SCOPE_ASSIGNMENT Node = 190
	SCOPE_BLOCK Node = 191
	SOFT_OVERRIDE_KEY Node = 192
	SOUND Node = 193
	SOUND_CONFIGURATION Node = 194
	SOUND_CONFIGURATION_LIST Node = 195
	STRING_ARRAY Node = 196
	STYLE_CONFIGURATION Node = 197
	STYLE_CONFIGURATION_LIST Node = 198
	STYLE_CONFIG_WRAP Node = 199
	STYLE_DEF Node = 200
	STYLE_REF Node = 201
	TARGET_SCHEMA_REF Node = 202
	TEMPLATE Node = 203
	TEMPLATE_ARGUMENT Node = 204
	TEMPLATE_CALL_ARG Node = 205
	TEMPLATE_CALL_ARGS Node = 206
	TEMPLATE_USAGE Node = 207
	TEXT_COLOR Node = 208
	TEXT_SIZE Node = 209
	THEME Node = 210
	THEME_SCHEMA Node = 211
	THEME_SCHEMA_STYLE_ENTRY Node = 212
	THEME_SCHEMA_STYLE_LIST Node = 213
	THEME_STYLE Node = 214
	THEME_STYLE_ENTRY Node = 215
	THEME_STYLE_LIST Node = 216
	VARIABLE_REF Node = 217
	VARIANTS_BLOCK Node = 218
	VARIANT_CONDITION Node = 219
	VERSION_STATEMENT Node = 220
	gr_ADAPTER_BODY Node = 221
	gr_BASELINE_PROPERTY Node = 222
	gr_COLORSET_ITEM_LIST Node = 223
	gr_COLOR_CONFIG Node = 224
	gr_COND_LEFT Node = 225
	gr_COND_OP Node = 226
	gr_CONFIGURATION_BODY Node = 227
	gr_CORE_CONDITION_STMT Node = 228
	gr_DESCRIPTION_STMT Node = 229
	gr_ENGINE_DIRECTIVE Node = 230
	gr_ENTITY_REF_WRAP Node = 231
	gr_FUNCTION_BODY Node = 232
	gr_HEX_LITERAL Node = 233
	gr_HSLA_LITERAL Node = 234
	gr_HSL_LITERAL Node = 235
	gr_HSVA_LITERAL Node = 236
	gr_HSV_LITERAL Node = 237
	gr_HUE_SHORTHAND Node = 238
	gr_MAIN_BLOCK_LIST Node = 239
	gr_MINIMAP_CONFIG Node = 240
	gr_MINIMAP_CONFIG_LIST Node = 241
	gr_MSTMT Node = 242
	gr_RGBA_LITERAL Node = 243
	gr_RGB_LITERAL Node = 244
	gr_RGB_SHORTHAND Node = 245
	gr_RULESET_BODY Node = 246
	gr_RULE_BODY Node = 247
	gr_RULE_PROPERTY Node = 248
	gr_SOFT_OVERRIDE_KEY Node = 249
	gr_SOUND_CONFIG Node = 250
	gr_SOUND_CONFIG_LIST Node = 251
	gr_STYLE_CONFIG Node = 252
	gr_STYLE_CONFIG_LIST Node = 253
	gr_STYLE_CONFIG_WRAP Node = 254
	gr_TEMPLATE_CALL_ARG Node = 255
	gr_THEME_EXTEND Node = 256
	gr_THEME_IMPLEMENT Node = 257
	gr_THEME_SCHEMA_STYLE_ENTRY Node = 258
	gr_THEME_SCHEMA_STYLE_LIST Node = 259
	gr_THEME_STYLE_ENTRY Node = 260
	gr_THEME_STYLE_LIST Node = 261
	gr_TextSize Node = 262
	gr_VSTMT Node = 263
)

var NodeNames = [...]string{
	"ACTION_DEF",
	"ADAPTER_BODY",
	"ADAPTER_DEF",
	"BACKGROUND",
	"BASELINE_BLOCK",
	"BASELINE_PROPERTY",
	"BORDER",
	"COLORSET",
	"COLORSET_ITEM",
	"COLORSET_ITEM_LIST",
	"COLOR_CONFIG",
	"COLOR_OVERRIDE",
	"COLOR_REF",
	"CONDITION_EXPR",
	"CONDITION_LEFT",
	"CONDITION_OPERATOR",
	"CONDITION_RIGHT",
	"CONFIGURATION",
	"CONFIGURATION_ASSIGNMENT",
	"CONFIGURATION_ASSIGNMENT_VALUE",
	"CONFIGURATION_BODY",
	"CORE_CONDITIONS",
	"CORE_CONDITION_STMT",
	"DESCRIPTION_STMT",
	"EFFECT",
	"ENGINE_DIRECTIVE",
	"ENTITY_REF_WRAP",
	"ERROR_NODE",
	"EXTEND_SEQUENCE",
	"FUNCTION",
	"FUNCTION_BODY",
	"FUNCTION_SIGNATURE",
	"HEX_LITERAL",
	"HSLA_LITERAL",
	"HSL_LITERAL",
	"HSVA_LITERAL",
	"HSV_LITERAL",
	"HUE_SHORTHAND",
	"IMPLEMENT_SEQUENCE",
	"IMPORT_STMT",
	"INCLUDE_STMT",
	"INHERIT_DEF",
	"MAIN_BLOCK",
	"MAIN_BLOCK_LIST",
	"MINIMAP",
	"MINIMAP_CONFIGURATION",
	"MINIMAP_CONFIGURATION_LIST",
	"MODULE_PATH",
	"MODULE_STATEMENT",
	"NodeActionDef",
	"NodeActionType",
	"NodeAdapter",
	"NodeAlpha",
	"NodeArgumentName",
	"NodeArgumentType",
	"NodeAssignTarget",
	"NodeAssignmentValue",
	"NodeBackground",
	"NodeBaselineBlock",
	"NodeBooleanLiteral",
	"NodeBorder",
	"NodeColorKey",
	"NodeColorKeyReference",
	"NodeColorOverride",
	"NodeColorReference",
	"NodeColorSet",
	"NodeColorSetEntry",
	"NodeColorSetName",
	"NodeColorSetReference",
	"NodeConditionExpr",
	"NodeConditionTarget",
	"NodeConditionValue",
	"NodeConfiguration",
	"NodeConfigurationEntry",
	"NodeConfigurationKey",
	"NodeConfigurationValue",
	"NodeCoreConditions",
	"NodeEffect",
	"NodeEffectColor",
	"NodeEffectTemporary",
	"NodeEngineDirective",
	"NodeExportKeyword",
	"NodeExtends",
	"NodeFunction",
	"NodeFunctionArgument",
	"NodeFunctionName",
	"NodeFunctionSignature",
	"NodeHexColor",
	"NodeHue",
	"NodeIdentifier",
	"NodeImplements",
	"NodeImport",
	"NodeIncludeRuleset",
	"NodeInheritDef",
	"NodeInheritTarget",
	"NodeIntLiteral",
	"NodeLightness",
	"NodeMainBlock",
	"NodeMinimap",
	"NodeMinimapColor",
	"NodeMinimapShape",
	"NodeMinimapSize",
	"NodeModuleAlias",
	"NodeModulePath",
	"NodeOnHide",
	"NodeOnShow",
	"NodeOp",
	"NodeOriginalSchemaKey",
	"NodeOriginalSchemaReference",
	"NodeOverride",
	"NodePathSegment",
	"NodePrivateKeyword",
	"NodeProgram",
	"NodeRGBAlpha",
	"NodeRGBBlue",
	"NodeRGBGreen",
	"NodeRGBRed",
	"NodeReferenceSegment",
	"NodeRule",
	"NodeRuleBlock",
	"NodeRuleName",
	"NodeRules",
	"NodeRuleset",
	"NodeRulesetDescription",
	"NodeRulesetName",
	"NodeRulesetOverride",
	"NodeRulesetOverrideEntry",
	"NodeRulesetOverrideKey",
	"NodeRulesetOverrideTarget",
	"NodeRulesetReference",
	"NodeRulesetReferenceSegment",
	"NodeSaturation",
	"NodeSchemaKeyAdapter",
	"NodeSchemaUsageTarget",
	"NodeScopeAssignment",
	"NodeScopeBlock",
	"NodeSound",
	"NodeSoundEnabled",
	"NodeSoundID",
	"NodeSoundPath",
	"NodeSoundPositional",
	"NodeSoundVolume",
	"NodeStringArray",
	"NodeStringLiteral",
	"NodeStyleDef",
	"NodeStyleKey",
	"NodeStyleKeyRef",
	"NodeStyleRef",
	"NodeTargetSchemaKey",
	"NodeTargetSchemaReference",
	"NodeTemplate",
	"NodeTemplateArguments",
	"NodeTemplateName",
	"NodeTemplateReferenceTarget",
	"NodeTemplateUsage",
	"NodeTextColor",
	"NodeTextSize",
	"NodeTheme",
	"NodeThemeName",
	"NodeThemeReference",
	"NodeThemeSchema",
	"NodeThemeSchemaName",
	"NodeThemeSchemaReference",
	"NodeThemeStyle",
	"NodeThemeStyleName",
	"NodeValue",
	"NodeVariableName",
	"NodeVariableRef",
	"NodeVariantCondition",
	"NodeVariantsBlock",
	"NodeVersionIndicator",
	"ON_HIDE_ACTION",
	"ON_SHOW_ACTION",
	"ORIGINAL_SCHEMA_REF",
	"RGBA_LITERAL",
	"RGB_LITERAL",
	"RGB_SHORTHAND",
	"RULE",
	"RULES",
	"RULESET",
	"RULESET_BODY",
	"RULESET_OVERRIDE",
	"RULESET_OVERRIDE_STMT",
	"RULESET_OVERRIDE_TARGET",
	"RULESET_REFERENCE",
	"RULE_BLOCK",
	"RULE_BODY",
	"RULE_PROPERTY",
	"SCHEMA_KEY_CONVERT_STMT",
	"SCOPE_ASSIGNMENT",
	"SCOPE_BLOCK",
	"SOFT_OVERRIDE_KEY",
	"SOUND",
	"SOUND_CONFIGURATION",
	"SOUND_CONFIGURATION_LIST",
	"STRING_ARRAY",
	"STYLE_CONFIGURATION",
	"STYLE_CONFIGURATION_LIST",
	"STYLE_CONFIG_WRAP",
	"STYLE_DEF",
	"STYLE_REF",
	"TARGET_SCHEMA_REF",
	"TEMPLATE",
	"TEMPLATE_ARGUMENT",
	"TEMPLATE_CALL_ARG",
	"TEMPLATE_CALL_ARGS",
	"TEMPLATE_USAGE",
	"TEXT_COLOR",
	"TEXT_SIZE",
	"THEME",
	"THEME_SCHEMA",
	"THEME_SCHEMA_STYLE_ENTRY",
	"THEME_SCHEMA_STYLE_LIST",
	"THEME_STYLE",
	"THEME_STYLE_ENTRY",
	"THEME_STYLE_LIST",
	"VARIABLE_REF",
	"VARIANTS_BLOCK",
	"VARIANT_CONDITION",
	"VERSION_STATEMENT",
	"gr_ADAPTER_BODY",
	"gr_BASELINE_PROPERTY",
	"gr_COLORSET_ITEM_LIST",
	"gr_COLOR_CONFIG",
	"gr_COND_LEFT",
	"gr_COND_OP",
	"gr_CONFIGURATION_BODY",
	"gr_CORE_CONDITION_STMT",
	"gr_DESCRIPTION_STMT",
	"gr_ENGINE_DIRECTIVE",
	"gr_ENTITY_REF_WRAP",
	"gr_FUNCTION_BODY",
	"gr_HEX_LITERAL",
	"gr_HSLA_LITERAL",
	"gr_HSL_LITERAL",
	"gr_HSVA_LITERAL",
	"gr_HSV_LITERAL",
	"gr_HUE_SHORTHAND",
	"gr_MAIN_BLOCK_LIST",
	"gr_MINIMAP_CONFIG",
	"gr_MINIMAP_CONFIG_LIST",
	"gr_MSTMT",
	"gr_RGBA_LITERAL",
	"gr_RGB_LITERAL",
	"gr_RGB_SHORTHAND",
	"gr_RULESET_BODY",
	"gr_RULE_BODY",
	"gr_RULE_PROPERTY",
	"gr_SOFT_OVERRIDE_KEY",
	"gr_SOUND_CONFIG",
	"gr_SOUND_CONFIG_LIST",
	"gr_STYLE_CONFIG",
	"gr_STYLE_CONFIG_LIST",
	"gr_STYLE_CONFIG_WRAP",
	"gr_TEMPLATE_CALL_ARG",
	"gr_THEME_EXTEND",
	"gr_THEME_IMPLEMENT",
	"gr_THEME_SCHEMA_STYLE_ENTRY",
	"gr_THEME_SCHEMA_STYLE_LIST",
	"gr_THEME_STYLE_ENTRY",
	"gr_THEME_STYLE_LIST",
	"gr_TextSize",
	"gr_VSTMT",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
