// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokAssignment Token = 2
	TokBlockComment Token = 3
	TokEOF Token = 4
	TokExclamation Token = 5
	TokIdentifier Token = 6
	TokLineComment Token = 7
	TokParenClose Token = 8
	TokParenOpen Token = 9
	TokPipe Token = 10
	TokPlus Token = 11
	TokQuestion Token = 12
	TokRange Token = 13
	TokSemi Token = 14
	TokStar Token = 15
	TokStringDoubleEnd Token = 16
	TokStringDoubleStart Token = 17
	TokStringDoubleText Token = 18
	TokStringEscape Token = 19
	TokStringSingleEnd Token = 20
	TokStringSingleStart Token = 21
	TokStringSingleText Token = 22
	TokTilde Token = 23
	TokWhitespace Token = 24
)

var TokenNames = [...]string{
	"TokAssignment",
	"TokBlockComment",
	"TokEOF",
	"TokExclamation",
	"TokIdentifier",
	"TokLineComment",
	"TokParenClose",
	"TokParenOpen",
	"TokPipe",
	"TokPlus",
	"TokQuestion",
	"TokRange",
	"TokSemi",
	"TokStar",
	"TokStringDoubleEnd",
	"TokStringDoubleStart",
	"TokStringDoubleText",
	"TokStringEscape",
	"TokStringSingleEnd",
	"TokStringSingleStart",
	"TokStringSingleText",
	"TokTilde",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	DOUBLE_QUOTE_STRING Node = 1
	ERROR_NODE Node = 2
	NodeAlternation Node = 3
	NodeCharRange Node = 4
	NodeNegation Node = 5
	NodeOneOrMore Node = 6
	NodeOpConcat Node = 7
	NodeOptional Node = 8
	NodeProduction Node = 9
	NodeProductionGroup Node = 10
	NodeProductionName Node = 11
	NodeProductionReference Node = 12
	NodeProductionSegment Node = 13
	NodeProgram Node = 14
	NodeStringEscape Node = 15
	NodeStringLiteral Node = 16
	NodeStringText Node = 17
	NodeZeroOrMore Node = 18
	PRODUCTION Node = 19
	PRODUCTION_EXPRESSION Node = 20
	PRODUCTION_GROUP Node = 21
	SINGLE_QUOTE_STRING Node = 22
	STRING_LITERAL Node = 23
	gr_STRING_LITERAL Node = 24
)

var NodeNames = [...]string{
	"DOUBLE_QUOTE_STRING",
	"ERROR_NODE",
	"NodeAlternation",
	"NodeCharRange",
	"NodeNegation",
	"NodeOneOrMore",
	"NodeOpConcat",
	"NodeOptional",
	"NodeProduction",
	"NodeProductionGroup",
	"NodeProductionName",
	"NodeProductionReference",
	"NodeProductionSegment",
	"NodeProgram",
	"NodeStringEscape",
	"NodeStringLiteral",
	"NodeStringText",
	"NodeZeroOrMore",
	"PRODUCTION",
	"PRODUCTION_EXPRESSION",
	"PRODUCTION_GROUP",
	"SINGLE_QUOTE_STRING",
	"STRING_LITERAL",
	"gr_STRING_LITERAL",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
