// Code generated by LangSpec. DO NOT EDIT.

package artifacts

import (
	"lexarch"
	"strconv"
)

// Token represents a Token generated by LangSpec (IDs match compiler symbol table).
type Token = lexarch.TokenKind

const (
	TokAssignment Token = 2
	TokBlockComment Token = 3
	TokEOF Token = 4
	TokIdentifier Token = 5
	TokLineComment Token = 6
	TokParenClose Token = 7
	TokParenOpen Token = 8
	TokPipe Token = 9
	TokPlus Token = 10
	TokQuestion Token = 11
	TokSemi Token = 12
	TokStar Token = 13
	TokStringLiteral Token = 14
	TokWhitespace Token = 15
)

var TokenNames = [...]string{
	"TokAssignment",
	"TokBlockComment",
	"TokEOF",
	"TokIdentifier",
	"TokLineComment",
	"TokParenClose",
	"TokParenOpen",
	"TokPipe",
	"TokPlus",
	"TokQuestion",
	"TokSemi",
	"TokStar",
	"TokStringLiteral",
	"TokWhitespace",
}

func TokenString(t lexarch.TokenKind) string {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "Token(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return TokenNames[t-2]
}

func TokenTokenKindStringResolver(t lexarch.TokenKind) (string, bool) {
	if t < 2 || int(t-2) >= len(TokenNames) {
		return "", false
	}
	return TokenNames[t-2], true
}

func init() {
	lexarch.TokenKindRegisterStringResolver(TokenTokenKindStringResolver)
}

// Node represents a Node generated by LangSpec (IDs match compiler symbol table).
type Node uint32

const (
	ERROR_NODE Node = 1
	NodeAlternation Node = 2
	NodeLexLiteral Node = 3
	NodeOneOrMore Node = 4
	NodeOpConcat Node = 5
	NodeOptional Node = 6
	NodeProduction Node = 7
	NodeProductionGroup Node = 8
	NodeProductionName Node = 9
	NodeProductionReference Node = 10
	NodeProductionSegment Node = 11
	NodeProgram Node = 12
	NodeZeroOrMore Node = 13
	PRODUCTION Node = 14
	PRODUCTION_EXPRESSION Node = 15
	PRODUCTION_GROUP Node = 16
)

var NodeNames = [...]string{
	"ERROR_NODE",
	"NodeAlternation",
	"NodeLexLiteral",
	"NodeOneOrMore",
	"NodeOpConcat",
	"NodeOptional",
	"NodeProduction",
	"NodeProductionGroup",
	"NodeProductionName",
	"NodeProductionReference",
	"NodeProductionSegment",
	"NodeProgram",
	"NodeZeroOrMore",
	"PRODUCTION",
	"PRODUCTION_EXPRESSION",
	"PRODUCTION_GROUP",
}

func (t Node) String() string {
	if t < 1 || int(t-1) >= len(NodeNames) {
		return "Node(" + strconv.FormatUint(uint64(t), 10) + ")"
	}
	return NodeNames[t-1]
}
